using Content.Client.UserInterface.Controls;
using Content.Shared._Nibiru.PlanetMap;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Nibiru.PlanetMap.UI;

[GenerateTypedNameReferences]
public sealed partial class PlanetMapWindow : FancyWindow
{
    public event Action? OnScanPressed;
    public event Action? OnCenterPressed;

    public PlanetMapWindow()
    {
        RobustXamlLoader.Load(this);

        ScanButton.OnPressed   += _ => OnScanPressed?.Invoke();
        CenterButton.OnPressed += _ => OnCenterPressed?.Invoke();
    }

    public void UpdatePlayerPosition(Vector2i tile)
    {
        MapControl.PlayerTile = tile;
    }

    public void CenterOnPlayer()
    {
        MapControl.CenterOnPlayer();
    }

    /// <summary>Clears all local chunk data (called on map-open signal before streaming starts).</summary>
    public void ClearChunks()
    {
        MapControl.ClearChunks();
    }

    public void MergeChunks(Dictionary<Vector2i, uint[]> newChunks,
                            Dictionary<Vector2i, uint[]> newObjects,
                            List<string>                 objectPrototypes)
    {
        MapControl.MergeChunks(newChunks, newObjects, objectPrototypes);
    }

    public void LoadSavedChunks(Dictionary<Vector2i, uint[]> chunks,
                                Dictionary<Vector2i, uint[]> objects,
                                List<string>                 objectPrototypes)
    {
        MapControl.LoadSavedChunks(chunks, objects, objectPrototypes);
    }
}
