using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Localization;
using System.Globalization;
using System.Numerics;

namespace Content.Client._Nibiru.LanguageSelect.UI;

[GenerateTypedNameReferences]
public sealed partial class LanguageSelectWindow : DefaultWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private ILocalizationManager _loc = default!;

    /// <summary>
    /// Raised when the player confirms their language choice.
    /// </summary>
    public event Action<CultureInfo>? OnLanguageSelected;

    // Map of culture name -> native display name
    private static readonly Dictionary<string, string> NativeNames = new()
    {
        { "en-US", "English" },
        { "ru-RU", Loc.GetString("language-name-russian") },
    };

    public LanguageSelectWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Don't allow closing without selecting a language
        OnClose += OnWindowClose;

        PopulateLanguageButtons();
    }

    private void PopulateLanguageButtons()
    {
        var cultures = _loc.GetFoundCultures();

        foreach (var culture in cultures)
        {
            // Only show languages that have a known native name (en-US, ru-RU)
            if (!NativeNames.TryGetValue(culture.Name, out var nativeName))
                continue;

            var button = new Button
            {
                Text = nativeName,
                HorizontalExpand = true,
                MinSize = new Vector2(0, 48),
                StyleClasses = { "OpenBoth" }
            };

            var captureCulture = culture;
            button.OnPressed += _ => SelectLanguage(captureCulture);

            LanguageButtonsContainer.AddChild(button);
        }
    }

    private void SelectLanguage(CultureInfo culture)
    {
        // Save to CVars (this triggers LocaleSwitchSystem through OnLanguageChanged)
        _cfg.SetCVar(CCVars.ClientLanguage, culture.Name);
        _cfg.SetCVar(CCVars.NibiruLanguageSelected, true);
        _cfg.SaveToFile();

        OnLanguageSelected?.Invoke(culture);
        Close();
    }

    private void OnWindowClose()
    {
        // If window is closed without selecting, default to en-US and mark as selected
        if (!_cfg.GetCVar(CCVars.NibiruLanguageSelected))
        {
            var enUS = CultureInfo.GetCultureInfo("en-US", predefinedOnly: false);
            SelectLanguage(enUS);
        }
    }
}
