using System;
using Content.Shared._Nibiru.NPC;
using Content.Shared._Nibiru.NPC.Training;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Maths;

namespace Content.Client._Nibiru.NPC.UI;

[GenerateTypedNameReferences]
public sealed partial class NibiruAnimalTrainingWindow : DefaultWindow
{
    public Action<NibiruAnimalCommand>? OnTrainCommand;
    public Action? OnTrainStress;

    public NibiruAnimalTrainingWindow()
    {
        RobustXamlLoader.Load(this);

        TrainStressButton.OnPressed += _ => OnTrainStress?.Invoke();
    }

    public void UpdateState(NibiruAnimalTrainingBuiState state)
    {
        // Trust Bar
        TrustBar.MaxValue = state.MaxTrust;
        TrustBar.Value = state.TrustLevel;
        TrustLabel.Text = $"{state.TrustLevel:F0} / {state.MaxTrust:F0}";

        // Stress Training
        StressContainer.Visible = state.HasMountFear;
        if (state.HasMountFear)
        {
            StressBar.MaxValue = state.MaxStressTraining;
            StressBar.Value = state.StressTraining;
            StressLabel.Text = $"{state.StressTraining:F0} / {state.MaxStressTraining:F0}";
            
            TrainStressButton.Disabled = state.StressTraining >= state.MaxStressTraining || state.TrustLevel < 30f;
        }

        // Commands
        CommandsContainer.Visible = state.Trainable;
        if (state.Trainable)
        {
            CommandsList.DisposeAllChildren();

            foreach (NibiruAnimalCommand command in Enum.GetValues(typeof(NibiruAnimalCommand)))
            {
                if (!state.PossibleCommands.Contains(command))
                    continue;

                var row = new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                };

                var name = Loc.GetString($"nibiru-animal-command-{command.ToString().ToLower()}");
                var label = new Label
                {
                    Text = name,
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center
                };

                var isLearned = state.LearnedCommands.Contains(command);
                var reqTrust = GetRequiredTrust(command);
                var canAfford = state.TrustLevel >= reqTrust;

                var button = new Button
                {
                    Text = isLearned ? Loc.GetString("nibiru-animal-training-learned") : Loc.GetString("nibiru-animal-training-teach"),
                    Disabled = isLearned || !canAfford,
                    ModulateSelfOverride = isLearned ? Color.Green : (!canAfford ? Color.Gray : Color.White),
                    ToolTip = isLearned ? "" : Loc.GetString("nibiru-animal-training-req-trust", ("trust", reqTrust))
                };

                if (!isLearned && canAfford)
                {
                    button.OnPressed += _ => OnTrainCommand?.Invoke(command);
                }

                row.AddChild(label);
                row.AddChild(button);
                CommandsList.AddChild(row);
            }
        }
    }

    private float GetRequiredTrust(NibiruAnimalCommand command)
    {
        return command switch
        {
            NibiruAnimalCommand.Follow => 50f,
            NibiruAnimalCommand.Stay => 75f,
            NibiruAnimalCommand.Attack => 100f,
            NibiruAnimalCommand.Grab => 110f,
            NibiruAnimalCommand.Guard => 120f,
            NibiruAnimalCommand.Search => 90f,
            _ => 50f
        };
    }
}
