using Content.Shared._Nibiru.NPC.Utility;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._Nibiru.NPC.UI;

[GenerateTypedNameReferences]
public sealed partial class NibiruBirdDeliveryWindow : DefaultWindow
{
    public Action<NetEntity>? OnPostSelected;

    public NibiruBirdDeliveryWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(NibiruBirdDeliveryUiState state)
    {
        PostsContainer.DisposeAllChildren();

        if (state.Posts.Count == 0)
        {
            PostsContainer.AddChild(new Label { Text = Loc.GetString("nibiru-bird-no-pigeon-lofts"), HorizontalAlignment = HAlignment.Center });
            return;
        }

        foreach (var (uid, name) in state.Posts)
        {
            var button = new Button
            {
                Text = name,
                Margin = new Robust.Shared.Maths.Thickness(0, 0, 0, 5)
            };

            button.OnPressed += _ =>
            {
                OnPostSelected?.Invoke(uid);
            };

            PostsContainer.AddChild(button);
        }
    }
}
