using Content.Shared._Nibiru.NPC.Utility;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._Nibiru.NPC.UI;

[GenerateTypedNameReferences]
public sealed partial class NibiruBirdPostRenameWindow : DefaultWindow
{
    public Action<string>? OnRename;

    public NibiruBirdPostRenameWindow()
    {
        RobustXamlLoader.Load(this);

        SaveButton.OnPressed += _ =>
        {
            if (string.IsNullOrWhiteSpace(NewNameLine.Text))
                return;
            OnRename?.Invoke(NewNameLine.Text);
        };
    }
}
