using Content.Client.Lathe;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using Content.Client.Construction;

using Content.Shared.Construction.Prototypes;

namespace Content.Client.Backmen.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class MiniRecipeCardControl : Control
{
    public MiniRecipeCardControl(TechnologyPrototype technology, 
								IPrototypeManager prototypeManager, 
								SpriteSystem sprite, 
								LatheSystem lathe, 
								ConstructionSystem ConstSys,
								LatheRecipePrototype? proto = null, 
								ConstructionPrototype? consProto = null)
    {
        RobustXamlLoader.Load(this);

        var discipline = prototypeManager.Index(technology.Discipline);
        Background.ModulateSelfOverride = discipline.Color;
		if(proto != null)
		{
			NameLabel.SetMessage(lathe.GetRecipeName(proto));
			
			if (proto.Result.HasValue)
				Showcase.Texture = sprite.Frame0(prototypeManager.Index(proto.Result.Value));

			if (proto.Description.HasValue)
			{
				var tooltip = new Tooltip();
				tooltip.SetMessage(FormattedMessage.FromUnformatted(lathe.GetRecipeDescription(proto)));
				Main.TooltipSupplier = _ => tooltip;
			}
		}
		
		if(consProto != null)
		{
			NameLabel.SetMessage(ConstSys.GetCraftName(consProto));
			
			if (!ConstSys!.TryGetRecipePrototype(consProto.ID, out var targetProtoId) || !prototypeManager.TryIndex(targetProtoId, out EntityPrototype? entity))
				return;
	
			Showcase.Texture = sprite.Frame0(prototypeManager.Index(entity));

			if (!string.IsNullOrWhiteSpace(consProto.Description))
			{
				var tooltip = new Tooltip();
				tooltip.SetMessage(FormattedMessage.FromUnformatted(consProto.Description));
				Main.TooltipSupplier = _ => tooltip;
			}
		}
    }
}
