using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Nibiru.Faction.UI;

// Код взят с Reserv
[GenerateTypedNameReferences]
public sealed partial class FactionRequestJoin : FancyWindow
{
    public event Action? OnAccept;
    public event Action? OnDeny;
    public FactionRequestJoin()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AcceptButton.OnPressed += _ => OnAccept?.Invoke();
        DenyButton.OnPressed += _ => OnDeny?.Invoke();
    }

    public void SetConverterName(string? text)
    {
        Title = Loc.GetString("faction-request-window-title");
        MessageText.Text = text == null ? Loc.GetString("faction-request-window-text") : Loc.GetString("faction-request-window-text-user", ("user", text));
    }
}
