- type: entity
  id: CEFoodPoppy
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: poppy
  description: A flower with extracts often used in the production of medicine.
  components:
  - type: Clothing
    slots:
    - HEAD
    quickEquip: false
  - type: Tag
    tags: [ Food, Plant ]
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - medicine
  - type: Sprite
    sprite: _Nibiru/Flora/Plants/poppy.rsi
    layers:
      - state: produce
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          produce: ""
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 22
        reagents:
        - ReagentId: CENutriment
          Quantity: 1
        - ReagentId: Bicaridine
          Quantity: 10
  - type: ToolRefinable
    qualityNeeded: Slicing
    refineTime: 1.5
    refineResult:
    - id: CESeedPoppy
      amount: 2

- type: entity
  id: CEFoodAloe
  parent: FoodInjectableBase
  categories: [ ForkFiltered ]
  name: aloe
  description: A fragrant plant with soothing properties.
  components:
  - type: Tag
    tags: [ Food, Plant ]
  - type: Item
    size: Tiny
  - type: FlavorProfile
    flavors:
      - medicine
  - type: Sprite
    sprite: _Nibiru/Flora/Plants/aloe.rsi
    layers:
      - state: produce
        map: [ "random" ]
  - type: RandomSprite
    available:
      - random:
          produce: ""
  - type: Material
  - type: Stack
    stackType: CEFoodAloe
    count: 1
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 20
        reagents:
        - ReagentId: Aloe
          Quantity: 5
        - ReagentId: Dermaline
          Quantity: 5
  - type: ToolRefinable
    qualityNeeded: Slicing
    refineTime: 1.5
    refineResult:
    - id: CESeedAloe
      amount: 2

- type: stack
  id: CEFoodAloe
  name: aloe
  icon: { sprite: _Nibiru/Flora/Plants/aloe.rsi, state: produce }
  spawn: CEFoodAloe
  maxCount: 30

- type: material
  id: CEFoodAloe
  stackEntity: CEFoodAloe
  name: aloe
  unit: materials-unit-piece
  icon: { sprite: _Nibiru/Flora/Plants/aloe.rsi, state: produce }
  color: "#80ffff"
  price: 2
