using System.Numerics;
using Content.Shared._Nibiru.WeaponAttackType;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Nibiru.WeaponAttackType.UI;

[GenerateTypedNameReferences]
public sealed partial class AttackTypeGrid : UIWidget
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private readonly List<AttackTypeButton> _buttons = new();

    /// <summary>
    /// Raised when user clicks an attack type button. Passes the index.
    /// </summary>
    public event Action<int>? OnAttackTypeSelected;

    public AttackTypeGrid()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Show(EntityUid weapon, List<string> attacks, int currentIndex)
    {
        AttackButtonContainer.RemoveAllChildren();
        _buttons.Clear();

        for (var i = 0; i < attacks.Count; i++)
        {
            var attackId = attacks[i];
            var index = i;

            if (!_proto.TryIndex(attackId, out AttackTypePrototype? proto))
                continue;

            var button = new AttackTypeButton
            {
                AttackIndex = index,
                ToolTip = proto.Name,
                MinSize = new Vector2(36, 36),
                MaxSize = new Vector2(48, 48),
                Margin = new Thickness(2),
                ToggleMode = true,
                StyleClasses = { "Button" },
            };

            if (proto.Icon is SpriteSpecifier.Texture tex)
            {
                var loadedTex = _resourceCache.GetResource<TextureResource>(tex.TexturePath);
                button.AddChild(new TextureRect
                {
                    Texture = loadedTex,
                    Stretch = TextureRect.StretchMode.KeepAspectCentered,
                    MinSize = new Vector2(28, 28),
                });
            }
            else if (proto.Icon is SpriteSpecifier.Rsi rsi)
            {
                var loadedRsi = _resourceCache.GetResource<RSIResource>(rsi.RsiPath);
                if (loadedRsi.RSI.TryGetState(rsi.RsiState, out var state))
                {
                    button.AddChild(new TextureRect
                    {
                        Texture = state.Frame0,
                        Stretch = TextureRect.StretchMode.KeepAspectCentered,
                        MinSize = new Vector2(28, 28),
                    });
                }
            }
            else
            {
                // Fallback: show first letter
                button.AddChild(new Label
                {
                    Text = proto.Name.Length > 0 ? proto.Name[..1] : "?",
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                });
            }

            button.OnPressed += _ =>
            {
                OnAttackTypeSelected?.Invoke(index);
            };

            _buttons.Add(button);
            AttackButtonContainer.AddChild(button);
        }

        UpdateHighlight(currentIndex);
        Visible = true;
    }

    public void Hide()
    {
        Visible = false;
        _buttons.Clear();
        AttackButtonContainer.RemoveAllChildren();
    }

    public void UpdateHighlight(int index)
    {
        for (var i = 0; i < _buttons.Count; i++)
        {
            _buttons[i].Pressed = i == index;
        }
    }

    private sealed class AttackTypeButton : Button
    {
        public int AttackIndex;
    }
}
