name: Сообщить о проблеме
description: Для проблем, которые не подходят под другие формы.
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время заполнить форму. Этот шаблон предназначен для проблем, которые не подходят под другие шаблоны.
        Для обратной связи или помощи по запуску Space Station 14 присоединяйтесь к нашему [Discord](https://discord.station14.ru).
  - type: input
    attributes:
      label: В какой версии возникла проблема?
      description: Версию можно найти в правом нижнем углу окна changelog в игре.
      placeholder: wizards/aa1337b
    validations:
      required: false
  - type: textarea
    attributes:
      label: Описание
      description: |
        Кратко и ясно опишите проблему.
        Если проблема визуальная, приложите скриншот.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Воспроизведение
      description: Перечислите шаги, необходимые для воспроизведения проблемы.
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Дополнительный контекст
      description: Любая другая информация, которая может помочь разобраться в проблеме.
    validations:
      required: false
