blank_issues_enabled: true
contact_links:
  - name: Предложение
    url: https://discord.gg/QmfeX6hD2d
    about: Свои предложения можете оставлять в канале "обратная-связь".
  - name: Сообщить об уязвимости
    url: https://discord.gg/QmfeX6hD2d
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности mr_samuel (442346226952962058), либо derex3687 (415178361447514113) в Discord.
