using Content.Shared._Nibiru.ModularCraft;
using Content.Shared._Nibiru.ModularCraft.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Shared.FixedPoint;
using Content.Client.UserInterface.Controls;
using System.Linq;

namespace Content.Client._Nibiru.ModularCraft.UI;

[GenerateTypedNameReferences]
public sealed partial class ModularCraftMenu : FancyWindow
{
[Dependency] private IPrototypeManager _proto = default!;

    public event Action<string>?                  OnItemTypeSelected;
    public event Action<string, string?, string?>? OnSlotChanged;
    public event Action?                           OnCraftPressed;

    private ModularCraftBUIState? _lastState;
    private string? _activeSlot;

    // Данные для селекторов
    private List<(string Id, string Name)> _itemTypeItems = new();
    private List<(string Id, string Name)> _moduleItems   = new();
    private List<(string Id, string Name)> _materialItems = new();

    // Подавляем отправку OnSlotChanged во время программных изменений UI
    private bool _suppressSlotChanged;

    public ModularCraftMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        // Материалы одинаковы для всех слотов
        _materialItems = _proto.EnumeratePrototypes<ModularMaterialPrototype>()
            .OrderBy(p => p.Quality)
            .Select(p => (p.ID, p.Name))
            .ToList();

        // Типы предметов
        _itemTypeItems = _proto.EnumeratePrototypes<ModularItemPrototype>()
            .Select(p => (p.ID, p.Name))
            .ToList();

        WeaponTypeSelector.SetItems(_itemTypeItems);
        WeaponTypeSelector.OnValueChanged += id =>
        {
            if (id != null) OnItemTypeSelected?.Invoke(id);
        };

        WeaponPreview.OnSlotHovered   += OnSlotHovered;
        WeaponPreview.OnSlotUnhovered += OnSlotUnhovered;
        WeaponPreview.OnSlotClicked   += OnSlotClicked;

        // OnValueChanged вызывается только при нажатии стрелки (не при SetItems/SetValueSilent)
        ShapeSelector.OnValueChanged    += _ => { if (!_suppressSlotChanged) CommitCurrentSlot(); };
        MaterialSelector.OnValueChanged += _ => { if (!_suppressSlotChanged) CommitCurrentSlot(); };

        CraftButton.OnPressed += _ => OnCraftPressed?.Invoke();
    }

    // ── Обновление из BUI ─────────────────────────────────────────────────────

    public void UpdateState(ModularCraftBUIState state)
    {
        _lastState = state;

        if (state.ItemType != null)
        {
            _suppressSlotChanged = true;
            WeaponTypeSelector.SetValueSilent(state.ItemType);
            _suppressSlotChanged = false;

            WeaponPreview.SetItemType(state.ItemType);
        }

        if (state.ItemType != null && _proto.TryIndex<ModularItemPrototype>(state.ItemType, out var itemProto))
        {
            var canCraft = true;
            foreach (var slotProto in itemProto.RequiredParts)
            {
                var slot   = slotProto.Id;
                var visual = new SlotVisualState();

                if (state.SlotConfigs.TryGetValue(slot, out var cfg))
                {
                    visual.ModuleId   = cfg.ModuleId;
                    visual.IsSelected = cfg.ModuleId != null && cfg.MaterialId != null;

                    if (cfg.MaterialId != null &&
                        _proto.TryIndex<ModularMaterialPrototype>(cfg.MaterialId, out var mat))
                    {
                        visual.MaterialColor   = Robust.Shared.Maths.Color.FromHex(mat.PreviewColor);
                        visual.MaterialTexture = mat.Texture;
                    }

                    if (cfg.ModuleId == null || cfg.MaterialId == null) canCraft = false;
                }
                else canCraft = false;

                WeaponPreview.SetSlotState(slot, visual);
            }

            CraftButton.Disabled  = !canCraft;
            CraftStatusLabel.Text = canCraft
                ? Loc.GetString("weapon-smithy-ready")
                : Loc.GetString("weapon-smithy-fill-all-slots");
        }

        // Если активный слот уже выбран — просто обновляем описания/статы, не трогая селекторы
        if (_activeSlot != null)
        {
            RefreshDescriptions();
            RefreshComboStats();
        }

        UpdateTotalStats(state);
    }

    // ── Hover / Click ─────────────────────────────────────────────────────────

    private void OnSlotHovered(string slot)
    {
        var visual = WeaponPreview.GetState(slot) ?? new SlotVisualState();
        visual.IsHovered = true;
        WeaponPreview.SetSlotState(slot, visual);
    }

    private void OnSlotUnhovered(string slot)
    {
        var visual = WeaponPreview.GetState(slot) ?? new SlotVisualState();
        visual.IsHovered = false;
        WeaponPreview.SetSlotState(slot, visual);
    }

    private void OnSlotClicked(string slot)
    {
        _activeSlot = slot;
        if (_lastState != null)
        {
            _suppressSlotChanged = true;
            ShowSlotConfig(slot, _lastState);
            _suppressSlotChanged = false;

            // После настройки UI — отправляем дефолты на сервер один раз
            CommitCurrentSlot();
        }
    }

    // ── Настройка слота (правая панель) ───────────────────────────────────────

    private void ShowSlotConfig(string slot, ModularCraftBUIState state)
    {
        NoSelectionPanel.Visible = false;
        SlotConfigPanel.Visible  = true;

        ActiveSlotLabel.Text = _proto.TryIndex<ModularPartPrototype>(slot, out var partProto)
            ? partProto.Name
            : slot;

        var validModules = _proto.EnumeratePrototypes<ModularModulePrototype>()
            .Where(p =>
                p.PartType.Id == slot &&
                (p.CompatibleItemTypes.Count == 0 ||
                 (state.ItemType != null && p.CompatibleItemTypes.Any(c => c.Id == state.ItemType))))
            .OrderBy(p => p.Name)
            .ToList();

        _moduleItems = validModules.Select(p => (p.ID, p.Name)).ToList();

        ShapeSelector.SetItems(_moduleItems);
        MaterialSelector.SetItems(_materialItems);

        // Восстанавливаем сохранённые выборы или берём первые доступные
        string? modId = null;
        string? matId = null;

        if (state.SlotConfigs.TryGetValue(slot, out var cfg))
        {
            modId = cfg.ModuleId ?? (_moduleItems.Count > 0 ? _moduleItems[0].Id : null);
            matId = cfg.MaterialId ?? (_materialItems.Count > 0 ? _materialItems[0].Id : null);
        }
        else
        {
            modId = _moduleItems.Count  > 0 ? _moduleItems[0].Id  : null;
            matId = _materialItems.Count > 0 ? _materialItems[0].Id : null;
        }

        if (modId != null) ShapeSelector.SetValueSilent(modId);
        if (matId != null) MaterialSelector.SetValueSilent(matId);

        RefreshDescriptions();
        RefreshComboStats();
    }

    /// <summary>Отправляет текущий выбор формы+материала на сервер.</summary>
    private void CommitCurrentSlot()
    {
        if (_activeSlot == null) return;
        var modId = ShapeSelector.CurrentId;
        var matId = MaterialSelector.CurrentId;
        OnSlotChanged?.Invoke(_activeSlot, modId, matId);
        RefreshDescriptions();
        RefreshComboStats();
    }

    private void RefreshDescriptions()
    {
        var modId = ShapeSelector.CurrentId;
        var matId = MaterialSelector.CurrentId;

        if (modId != null && _proto.TryIndex<ModularModulePrototype>(modId, out var mod))
        {
            ModuleDescLabel.SetMessage(mod.Description);
            SlotCostLabel.Text = Loc.GetString("weapon-smithy-material-cost", ("n", mod.MaterialCost));
        }

        if (matId != null && _proto.TryIndex<ModularMaterialPrototype>(matId, out var mat))
        {
            MaterialDescLabel.SetMessage(mat.Description);
        }
    }

    private void RefreshComboStats()
    {
        var moduleId   = ShapeSelector.CurrentId;
        var materialId = MaterialSelector.CurrentId;

        if (moduleId == null || materialId == null ||
            !_proto.TryIndex<ModularModulePrototype>(moduleId,   out var mod) ||
            !_proto.TryIndex<ModularMaterialPrototype>(materialId, out var mat))
        {
            ComboStatDamage.Text = ComboStatPen.Text = ComboStatSpeed.Text = ComboStatWeight.Text = "";
            return;
        }

        var dmg    = (mod.DamageBonus + FixedPoint2.New(2f)) * mat.DamageMultiplier;
        var pen    = mod.PenetrationBonus * mat.PenetrationMultiplier;
        var speed  = mod.AttackSpeedMultiplier;
        var weight = mod.Weight * mat.WeightMultiplier;

        ComboStatDamage.Text = Loc.GetString("weapon-smithy-stat-damage", ("v", dmg));
        ComboStatPen.Text    = Loc.GetString("weapon-smithy-stat-pen",    ("v", pen));
        ComboStatSpeed.Text  = Loc.GetString("weapon-smithy-stat-speed",  ("v", speed));
        ComboStatWeight.Text = Loc.GetString("weapon-smithy-stat-weight", ("v", weight));
    }

    private void UpdateTotalStats(ModularCraftBUIState state)
    {
        var dmg    = FixedPoint2.Zero;
        var reach  = FixedPoint2.Zero;
        var weight = FixedPoint2.Zero;
        var pen    = FixedPoint2.Zero;

        foreach (var kvp in state.SlotConfigs)
        {
            var cfg = kvp.Value;
            if (cfg.ModuleId == null || cfg.MaterialId == null) continue;
            if (!_proto.TryIndex<ModularModulePrototype>(cfg.ModuleId,     out var mod)) continue;
            if (!_proto.TryIndex<ModularMaterialPrototype>(cfg.MaterialId,  out var mat)) continue;

            dmg    += (mod.DamageBonus + FixedPoint2.New(2f)) * mat.DamageMultiplier;
            reach  += mod.ReachBonus;
            weight += mod.Weight * mat.WeightMultiplier;
            pen    += mod.PenetrationBonus * mat.PenetrationMultiplier;
        }

        StatDamageLabel.Text = Loc.GetString("weapon-smithy-total-damage", ("v", dmg));
        StatReachLabel.Text  = Loc.GetString("weapon-smithy-total-reach",  ("v", reach));
        StatWeightLabel.Text = Loc.GetString("weapon-smithy-total-weight", ("v", weight));
        StatPenLabel.Text    = Loc.GetString("weapon-smithy-total-pen",    ("v", pen));
    }
}
