using Content.Client.Humanoid;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Sprite;
using Content.Shared.CCVar;
using Content.Shared.GameTicking;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Maths;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;
using Direction = Robust.Shared.Maths.Direction;
using static Content.Client.Corvax.SponsorOnlyHelpers; // Corvax-Sponsors
using Content.Client.Corvax.TTS; // Corvax-TTS
using Content.Shared._Nibiru.Factions;
using Content.Client.UserInterface.Systems.Faction.UI;
using Robust.Client.ResourceManagement;
using Robust.Shared.Input;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly IResourceManager _resManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;
        private readonly LobbyUIController _controller;

        private readonly SpriteSystem _sprite;

        // CCvar.
        private int _maxNameLength;

        /// <summary>
        /// If we're attempting to save.
        /// </summary>
        public event Action? Save;

        /// <summary>
        /// The character slot for the current profile.
        /// </summary>
        public int? CharacterSlot;

        /// <summary>
        /// The work in progress profile being edited.
        /// </summary>
        public HumanoidCharacterProfile? Profile;

        private Direction _previewRotation = Direction.North;

        private Color _factionBrushColor = Color.White;
        private Color _factionBgColor = Color.Transparent;
        private Color[] _factionPixels = new Color[16 * 16];
        private PanelContainer[] _factionPixelPanels = new PanelContainer[16 * 16];
        private Color[] _factionPixels8x8 = new Color[8 * 8];
        private PanelContainer[] _factionPixelPanels8x8 = new PanelContainer[8 * 8];
        private bool _factionIsDrawing = false;
        private bool _factionIsRightDrawing = false;
        private string? _selectedFactionRoleName = null;

        private static readonly ProtoId<GuideEntryPrototype> DefaultSpeciesGuidebook = "Species";
        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        private ISawmill _sawmill;

        private MarkingsViewModel _markingsModel = new();

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings)
        {
            RobustXamlLoader.Load(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            _resManager = resManager;
            _requirements = requirements;
            _controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _sprite = _entManager.System<SpriteSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);

            Markings.SetModel(_markingsModel);

            ImportButton.OnPressed += args =>
            {
                ImportProfile();
            };

            ExportButton.OnPressed += args =>
            {
                ExportProfile();
            };

            ExportImageButton.OnPressed += args =>
            {
                ExportImage();
            };

            OpenImagesButton.OnPressed += args =>
            {
                _resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            };

            ResetButton.OnPressed += args =>
            {
                SetProfile((HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
            };

            SaveButton.OnPressed += args =>
            {
                Save?.Invoke();
            };

            #region Left

            #region Name

            NameEdit.OnTextChanged += args => { SetName(args.Text); };
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            NameRandomize.OnPressed += args => RandomizeName();
            RandomizeEverythingButton.OnPressed += args => { RandomizeEverything(); };
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");

            #endregion Name

            #region Appearance

            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));

            #region Sex

            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex)args.Id);
            };

            #endregion Sex

            #region Age

            AgeEdit.OnTextChanged += args =>
            {
                if (!int.TryParse(args.Text, out var newAge))
                    return;

                SetAge(newAge);
            };

            #endregion Age

            #region Gender

            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int)Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int)Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int)Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int)Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender)args.Id);
            };

            #endregion Gender

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                OnSkinColorOnValueChanged();
            };

            #region Skin

            Skin.OnValueChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
            _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV
            _rgbSkinColorSelector.OnColorChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            #endregion

            #region SpawnPriority

            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"), (int)value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference)args.Id);
            };

            #endregion SpawnPriority

            #region Eyes

            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithEyeColor(newColor));
                _markingsModel.SetOrganEyeColor(Profile.Appearance.EyeColor);
                ReloadProfilePreview();
            };

            #endregion Eyes

            #endregion Appearance

            #region Jobs

            // TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-jobs-tab"));

            /*
            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-stay-in-lobby-button"),
                (int)PreferenceUnavailableMode.StayInLobby);
            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-spawn-as-overflow-button",
                              ("overflowJob", Loc.GetString(SharedGameTicker.FallbackOverflowJobName))),
                (int)PreferenceUnavailableMode.SpawnAsOverflow);

            PreferenceUnavailableButton.OnItemSelected += args =>
            {
                PreferenceUnavailableButton.SelectId(args.Id);
                Profile = Profile?.WithPreferenceUnavailable((PreferenceUnavailableMode)args.Id);
                SetDirty();
            };
            */

            _jobCategories = new Dictionary<string, BoxContainer>();

            // RefreshAntags();
            // RefreshJobs();

            #endregion Jobs

            // TabContainer.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-antags-tab"));

            RefreshTraits();

            TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-traits-tab")); // Corvax-TTS-Edit

            #region Markings

            TabContainer.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-markings-tab"));

            _markingsModel.MarkingsChanged += (_, _) => OnMarkingChange();
            _markingsModel.MarkingsReset += OnMarkingChange;

            #endregion Markings

            #region Factions
            TabContainer.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-faction-tab"));

            FactionSubTabs.SetTabTitle(0, "Основное");
            FactionSubTabs.SetTabTitle(1, "Логотип");
            FactionSubTabs.SetTabTitle(2, "Роли");
            FactionSubTabs.SetTabTitle(3, "Фильтры");

            FactionNameEdit.OnTextChanged += args => { Profile = Profile?.WithFactionName(args.Text); IsDirty = true; };
            FactionDescEdit.OnTextChanged += args => { Profile = Profile?.WithFactionDescription(args.Text); IsDirty = true; };
            FactionColorEdit.OnTextChanged += args => { Profile = Profile?.WithFactionColor(args.Text); IsDirty = true; };
            FactionIconEdit.OnTextChanged += args => { Profile = Profile?.WithFactionIcon(args.Text); IsDirty = true; };
            FactionRecruitingCheck.OnToggled += args => { Profile = Profile?.WithFactionRecruiting(args.Pressed); IsDirty = true; };

            InitializeFactionLogoEditor();
            InitializeFactionRolesEditor();
            InitializeFactionFiltersEditor();
            #endregion Factions

            RefreshFlavorText();

            RefreshVoiceTab(); // Corvax-TTS

            #region Dummy

            SpriteRotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCw();
                SetPreviewRotation(_previewRotation);
            };
            SpriteRotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCcw();
                SetPreviewRotation(_previewRotation);
            };

            #endregion Dummy

            #endregion Left

            ShowClothes.OnToggled += args =>
            {
                ReloadPreview();
            };

            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;

            UpdateSpeciesGuidebookIcon();
            IsDirty = false;
        }

<<<<<<< HEAD
        /// <summary>
        /// Refreshes the flavor text editor status.
        /// </summary>
        public void RefreshFlavorText()
        {
            if (_allowFlavorText)
            {
                if (_flavorText != null)
                    return;

                _flavorText = new FlavorText.FlavorText();
                TabContainer.AddChild(_flavorText);
                TabContainer.SetTabTitle(TabContainer.ChildCount - 1, Loc.GetString("humanoid-profile-editor-flavortext-tab"));
                _flavorTextEdit = _flavorText.CFlavorTextInput;

                _flavorText.OnFlavorTextChanged += OnFlavorTextChange;
            }
            else
            {
                if (_flavorText == null)
                    return;

                TabContainer.RemoveChild(_flavorText);
                _flavorText.OnFlavorTextChanged -= OnFlavorTextChange;
                _flavorText.Dispose();
                _flavorTextEdit?.Dispose();
                _flavorTextEdit = null;
                _flavorText = null;
            }
        }

        // Corvax-TTS-Start
        #region Voice

        private void RefreshVoiceTab()
        {
            if (!_cfgManager.GetCVar(CCCVars.TTSEnabled))
                return;

            _ttsTab = new TTSTab();
            var children = new List<Control>();
            foreach (var child in TabContainer.Children)
                children.Add(child);

            TabContainer.RemoveAllChildren();

            for (int i = 0; i < children.Count; i++)
            {
                if (i == 1) // Set the tab to the 2nd place.
                {
                    TabContainer.AddChild(_ttsTab);
                }
                TabContainer.AddChild(children[i]);
            }

            TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-voice-tab"));

            _ttsTab.OnVoiceSelected += voiceId =>
            {
                SetVoice(voiceId);
                _ttsTab.SetSelectedVoice(voiceId);
            };

            _ttsTab.OnPreviewRequested += voiceId =>
            {
                _entManager.System<TTSSystem>().RequestPreviewTTS(voiceId);
            };
        }

        private void UpdateTTSVoicesControls()
        {
            if (Profile is null || _ttsTab is null)
                return;

            _ttsTab.UpdateControls(Profile, Profile.Sex);
            _ttsTab.SetSelectedVoice(Profile.Voice);
        }

        #endregion
        // Corvax-TTS-End

        /// <summary>
        /// Refreshes traits selector
        /// </summary>
        public void RefreshTraits()
        {
            TraitsList.RemoveAllChildren();

            var traits = _prototypeManager.EnumeratePrototypes<TraitPrototype>().OrderBy(t => Loc.GetString(t.Name)).ToList();
            // TabContainer.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-traits-tab")); // Corvax-TTS-Edit

            if (traits.Count < 1)
            {
                TraitsList.AddChild(new Label
                {
                    Text = Loc.GetString("humanoid-profile-editor-no-traits"),
                    FontColorOverride = Color.Gray,
                });
                return;
            }

            // Setup model
            Dictionary<string, List<string>> traitGroups = new();
            List<string> defaultTraits = new();
            traitGroups.Add(TraitCategoryPrototype.Default, defaultTraits);

            foreach (var trait in traits)
            {
                if (trait.Category == null)
                {
                    defaultTraits.Add(trait.ID);
                    continue;
                }

                if (!_prototypeManager.HasIndex(trait.Category))
                    continue;

                var group = traitGroups.GetOrNew(trait.Category);
                group.Add(trait.ID);
            }

            // Create UI view from model
            foreach (var (categoryId, categoryTraits) in traitGroups)
            {
                TraitCategoryPrototype? category = null;

                if (categoryId != TraitCategoryPrototype.Default)
                {
                    category = _prototypeManager.Index<TraitCategoryPrototype>(categoryId);
                    // Label
                    TraitsList.AddChild(new Label
                    {
                        Text = Loc.GetString(category.Name),
                        Margin = new Thickness(0, 10, 0, 0),
                        StyleClasses = { StyleClass.LabelHeading },
                    });
                }

                List<TraitPreferenceSelector?> selectors = new();
                var selectionCount = 0;

                foreach (var traitProto in categoryTraits)
                {
                    var trait = _prototypeManager.Index<TraitPrototype>(traitProto);
                    var selector = new TraitPreferenceSelector(trait);

                    selector.Preference = Profile?.TraitPreferences.Contains(trait.ID) == true;
                    if (selector.Preference)
                        selectionCount += trait.Cost;

                    selector.PreferenceChanged += preference =>
                    {
                        if (preference)
                        {
                            Profile = Profile?.WithTraitPreference(trait.ID, _prototypeManager);
                        }
                        else
                        {
                            Profile = Profile?.WithoutTraitPreference(trait.ID, _prototypeManager);
                        }

                        SetDirty();
                        RefreshTraits(); // If too many traits are selected, they will be reset to the real value.
                    };
                    selectors.Add(selector);
                }

                // Selection counter
                if (category is { MaxTraitPoints: >= 0 })
                {
                    TraitsList.AddChild(new Label
                    {
                        Text = Loc.GetString("humanoid-profile-editor-trait-count-hint", ("current", selectionCount), ("max", category.MaxTraitPoints)),
                        FontColorOverride = Color.Gray
                    });
                }

                foreach (var selector in selectors)
                {
                    if (selector == null)
                        continue;

                    if (category is { MaxTraitPoints: >= 0 } &&
                        selector.Cost + selectionCount > category.MaxTraitPoints)
                    {
                        selector.Checkbox.Label.FontColorOverride = Color.Red;
                    }

                    TraitsList.AddChild(selector);
                }
            }
        }

        /// <summary>
        /// Refreshes the species selector.
        /// </summary>
        public void RefreshSpecies()
        {
            SpeciesButton.Clear();
            _species.Clear();

            _species.AddRange(_prototypeManager.EnumeratePrototypes<SpeciesPrototype>().Where(o => o.RoundStart));
            _species.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.CurrentCultureIgnoreCase));
            var speciesIds = _species.Select(o => o.ID).ToList();

            for (var i = 0; i < _species.Count; i++)
            {
                var name = Loc.GetString(_species[i].Name);

                if (_species[i].SponsorOnly) // Corvax-Sponsors
                    name += GetSponsorOnlySuffix();

                SpeciesButton.AddItem(name, i);

                if (Profile?.Species.Equals(_species[i].ID) == true)
                {
                    SpeciesButton.SelectId(i);
                }
            }

            // If our species isn't available then reset it to default.
            if (Profile != null)
            {
                if (!speciesIds.Contains(Profile.Species))
                {
                    SetSpecies(SharedHumanoidAppearanceSystem.DefaultSpecies);
                }
            }
        }

        public void RefreshAntags()
        {
            // AntagList.RemoveAllChildren();
            var items = new[]
            {
                ("humanoid-profile-editor-antag-preference-yes-button", 0),
                ("humanoid-profile-editor-antag-preference-no-button", 1)
            };

            foreach (var antag in _prototypeManager.EnumeratePrototypes<AntagPrototype>().OrderBy(a => Loc.GetString(a.Name)))
            {
                if (!antag.SetPreference)
                    continue;

                var antagContainer = new BoxContainer()
                {
                    Orientation = LayoutOrientation.Horizontal,
                };

                var selector = new RequirementsSelector()
                {
                    Margin = new Thickness(3f, 3f, 3f, 0f),
                };
                selector.OnOpenGuidebook += OnOpenGuidebook;

                var title = Loc.GetString(antag.Name);
                var description = Loc.GetString(antag.Objective);
                selector.Setup(items, title, 250, description, guides: antag.Guides);
                selector.Select(Profile?.AntagPreferences.Contains(antag.ID) == true ? 0 : 1);

                if (!_requirements.IsAllowed(
                        antag,
                        (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                        out var reason))
                {
                    selector.LockRequirements(reason);
                    Profile = Profile?.WithAntagPreference(antag.ID, false);
                    SetDirty();
                }
                else
                {
                    selector.UnlockRequirements();
                }

                selector.OnSelected += preference =>
                {
                    Profile = Profile?.WithAntagPreference(antag.ID, preference == 0);
                    SetDirty();
                };

                antagContainer.AddChild(selector);

                antagContainer.AddChild(new Button()
                {
                    Disabled = true,
                    Text = Loc.GetString("loadout-window"),
                    HorizontalAlignment = HAlignment.Right,
                    Margin = new Thickness(3f, 0f, 0f, 0f),
                });

                // AntagList.AddChild(antagContainer);
            }
        }

=======
>>>>>>> f92f9400ae31d5fd93e16a58e6257a15a51f220e
        private void SetDirty()
        {
            // If it equals default then reset the button.
            if (Profile == null || _preferencesManager.Preferences?.SelectedCharacter.MemberwiseEquals(Profile) == true)
            {
                IsDirty = false;
                return;
            }

            // TODO: Check if profile matches default.
            IsDirty = true;
        }

        /// <summary>
        /// Reloads the entire dummy entity for preview.
        /// </summary>
        /// <remarks>
        /// This is expensive so not recommended to run if you have a slider.
        /// </remarks>
        private void ReloadPreview()
        {
            if (Profile == null)
                return;

            SpriteView.LoadPreview(Profile, JobOverride, ShowClothes.Pressed);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        /// <summary>
        /// Resets the profile to the defaults.
        /// </summary>
        public void ResetToDefault()
        {
            SetProfile(
                (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                _preferencesManager.Preferences?.SelectedCharacterIndex);
        }

        /// <summary>
        /// Sets the editor to the specified profile with the specified slot.
        /// </summary>
        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            CharacterSlot = slot;
            IsDirty = false;
            JobOverride = null;

            UpdateNameEdit();
            UpdateFlavorTextEdit();
            UpdateSexControls();
            UpdateGenderControls();
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();
            UpdateTTSVoicesControls(); // Corvax-TTS
<<<<<<< HEAD
            UpdateHairPickers();
            UpdateCMarkingsHair();
            UpdateCMarkingsFacialHair();
            UpdateFactionControls();
=======
>>>>>>> f92f9400ae31d5fd93e16a58e6257a15a51f220e

            // RefreshAntags();
            // RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            RefreshTraits();
            RefreshFlavorText();
            ReloadPreview();

            /*
            if (Profile != null)
            {
                PreferenceUnavailableButton.SelectId((int)Profile.PreferenceUnavailable);
            }
            */
        }

        /// <summary>
        /// A slim reload that only updates the entity itself and not any of the job entities, etc.
        /// </summary>
        private void ReloadProfilePreview()
        {
            if (Profile == null)
                return;

            SpriteView.ReloadProfilePreview(Profile);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

<<<<<<< HEAD
        private void OnSpeciesInfoButtonPressed(BaseButton.ButtonEventArgs args)
        {
            // TODO GUIDEBOOK
            // make the species guide book a field on the species prototype.
            // I.e., do what jobs/antags do.

            var guidebookController = UserInterfaceManager.GetUIController<GuidebookUIController>();
            var species = Profile?.Species ?? SharedHumanoidAppearanceSystem.DefaultSpecies;
            var page = DefaultSpeciesGuidebook;
            if (_prototypeManager.HasIndex<GuideEntryPrototype>(species))
                page = new ProtoId<GuideEntryPrototype>(species.Id); // Gross. See above todo comment.

            if (_prototypeManager.Resolve(DefaultSpeciesGuidebook, out var guideRoot))
            {
                var dict = new Dictionary<ProtoId<GuideEntryPrototype>, GuideEntry>();
                dict.Add(DefaultSpeciesGuidebook, guideRoot);
                //TODO: Don't close the guidebook if its already open, just go to the correct page
                guidebookController.OpenGuidebook(dict, includeChildren:true, selected: page);
            }
        }

        /// <summary>
        /// Refreshes all job selectors.
        /// </summary>
        public void RefreshJobs()
        {
            // JobList.RemoveAllChildren();
            _jobCategories.Clear();
            _jobPriorities.Clear();
            var firstCategory = true;

            // Get all displayed departments
            var departments = new List<DepartmentPrototype>();
            foreach (var department in _prototypeManager.EnumeratePrototypes<DepartmentPrototype>())
            {
                if (department.EditorHidden)
                    continue;

                departments.Add(department);
            }

            departments.Sort(DepartmentUIComparer.Instance);

            var items = new[]
            {
                ("humanoid-profile-editor-job-priority-never-button", (int) JobPriority.Never),
                ("humanoid-profile-editor-job-priority-low-button", (int) JobPriority.Low),
                ("humanoid-profile-editor-job-priority-medium-button", (int) JobPriority.Medium),
                ("humanoid-profile-editor-job-priority-high-button", (int) JobPriority.High),
            };

            foreach (var department in departments)
            {
                var departmentName = Loc.GetString(department.Name);

                if (!_jobCategories.TryGetValue(department.ID, out var category))
                {
                    category = new BoxContainer
                    {
                        Orientation = LayoutOrientation.Vertical,
                        Name = department.ID,
                        ToolTip = Loc.GetString("humanoid-profile-editor-jobs-amount-in-department-tooltip",
                            ("departmentName", departmentName))
                    };

                    if (firstCategory)
                    {
                        firstCategory = false;
                    }
                    else
                    {
                        category.AddChild(new Control
                        {
                            MinSize = new Vector2(0, 23),
                        });
                    }

                    category.AddChild(new PanelContainer
                    {
                        PanelOverride = new StyleBoxFlat {BackgroundColor = Color.FromHex("#464966")},
                        Children =
                        {
                            new Label
                            {
                                Text = Loc.GetString("humanoid-profile-editor-department-jobs-label",
                                    ("departmentName", departmentName)),
                                Margin = new Thickness(5f, 0, 0, 0)
                            }
                        }
                    });

                    _jobCategories[department.ID] = category;
                    // JobList.AddChild(category);
                }

                var jobs = department.Roles.Select(jobId => _prototypeManager.Index(jobId))
                    .Where(job => job.SetPreference)
                    .ToArray();

                Array.Sort(jobs, JobUIComparer.Instance);

                foreach (var job in jobs)
                {
                    var jobContainer = new BoxContainer()
                    {
                        Orientation = LayoutOrientation.Horizontal,
                    };

                    var selector = new RequirementsSelector()
                    {
                        Margin = new Thickness(3f, 3f, 3f, 0f),
                    };
                    selector.OnOpenGuidebook += OnOpenGuidebook;

                    var icon = new TextureRect
                    {
                        TextureScale = new Vector2(2, 2),
                        VerticalAlignment = VAlignment.Center
                    };
                    var jobIcon = _prototypeManager.Index(job.Icon);
                    icon.Texture = _sprite.Frame0(jobIcon.Icon);
                    selector.Setup(items, job.LocalizedName, 200, job.LocalizedDescription, icon, job.Guides);

                    if (!_requirements.IsAllowed(job, (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, out var reason))
                    {
                        selector.LockRequirements(reason);
                    }
                    else
                    {
                        selector.UnlockRequirements();
                    }

                    selector.OnSelected += selectedPrio =>
                    {
                        var selectedJobPrio = (JobPriority) selectedPrio;
                        Profile = Profile?.WithJobPriority(job.ID, selectedJobPrio);

                        foreach (var (jobId, other) in _jobPriorities)
                        {
                            // Sync other selectors with the same job in case of multiple department jobs
                            if (jobId == job.ID)
                            {
                                other.Select(selectedPrio);
                                continue;
                            }

                            if (selectedJobPrio != JobPriority.High || (JobPriority) other.Selected != JobPriority.High)
                                continue;

                            // Lower any other high priorities to medium.
                            other.Select((int)JobPriority.Medium);
                            Profile = Profile?.WithJobPriority(jobId, JobPriority.Medium);
                        }

                        // TODO: Only reload on high change (either to or from).
                        ReloadPreview();

                        UpdateJobPriorities();
                        SetDirty();
                    };

                    var loadoutWindowBtn = new Button()
                    {
                        Text = Loc.GetString("loadout-window"),
                        HorizontalAlignment = HAlignment.Right,
                        VerticalAlignment = VAlignment.Center,
                        Margin = new Thickness(3f, 3f, 0f, 0f),
                    };

                    var collection = IoCManager.Instance!;
                    var protoManager = collection.Resolve<IPrototypeManager>();

                    // If no loadout found then disabled button
                    if (!protoManager.TryIndex<RoleLoadoutPrototype>(LoadoutSystem.GetJobPrototype(job.ID), out var roleLoadoutProto))
                    {
                        loadoutWindowBtn.Disabled = true;
                    }
                    // else
                    else
                    {
                        loadoutWindowBtn.OnPressed += args =>
                        {
                            RoleLoadout? loadout = null;

                            // Clone so we don't modify the underlying loadout.
                            Profile?.Loadouts.TryGetValue(LoadoutSystem.GetJobPrototype(job.ID), out loadout);
                            loadout = loadout?.Clone();

                            if (loadout == null)
                            {
                                loadout = new RoleLoadout(roleLoadoutProto.ID);
                                loadout.SetDefault(Profile, _playerManager.LocalSession, _prototypeManager);
                            }

                            OpenLoadout(job, loadout, roleLoadoutProto);
                        };
                    }

                    _jobPriorities.Add((job.ID, selector));
                    jobContainer.AddChild(selector);
                    jobContainer.AddChild(loadoutWindowBtn);
                    category.AddChild(jobContainer);
                }
            }

            UpdateJobPriorities();
        }

        private void OpenLoadout(JobPrototype? jobProto, RoleLoadout roleLoadout, RoleLoadoutPrototype roleLoadoutProto)
        {
            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
            var collection = IoCManager.Instance;

            if (collection == null || _playerManager.LocalSession == null || Profile == null)
                return;

            JobOverride = jobProto;
            var session = _playerManager.LocalSession;

            _loadoutWindow = new LoadoutWindow(Profile, roleLoadout, roleLoadoutProto, _playerManager.LocalSession, collection)
            {
                Title = Loc.GetString("loadout-window-title-loadout", ("job", $"{jobProto?.LocalizedName}")),
            };

            // Refresh the buttons etc.
            _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
            _loadoutWindow.OpenCenteredLeft();

            _loadoutWindow.OnNameChanged += name =>
            {
                roleLoadout.EntityName = name;
                Profile = Profile.WithLoadout(roleLoadout);
                SetDirty();
            };

            _loadoutWindow.OnLoadoutPressed += (loadoutGroup, loadoutProto) =>
            {
                roleLoadout.AddLoadout(loadoutGroup, loadoutProto, _prototypeManager);
                _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
                Profile = Profile?.WithLoadout(roleLoadout);
                ReloadPreview();
            };

            _loadoutWindow.OnLoadoutUnpressed += (loadoutGroup, loadoutProto) =>
            {
                roleLoadout.RemoveLoadout(loadoutGroup, loadoutProto, _prototypeManager);
                _loadoutWindow.RefreshLoadouts(roleLoadout, session, collection);
                Profile = Profile?.WithLoadout(roleLoadout);
                ReloadPreview();
            };

            JobOverride = jobProto;
            ReloadPreview();

            _loadoutWindow.OnClose += () =>
            {
                JobOverride = null;
                ReloadPreview();
            };

            if (Profile is null)
                return;

            UpdateJobPriorities();
        }

        private void OnFlavorTextChange(string content)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithFlavorText(content);
            SetDirty();
        }

        private void OnMarkingChange(MarkingSet markings)
        {
            if (Profile is null)
                return;

            Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithMarkings(markings.GetForwardEnumerator().ToList()));
            ReloadProfilePreview();
        }

        private void OnSkinColorOnValueChanged()
        {
            if (Profile is null) return;

            var skin = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
            var strategy = _prototypeManager.Index(skin).Strategy;

            switch (strategy.InputType)
            {
                case SkinColorationStrategyInput.Unary:
                {
                    if (!Skin.Visible)
                    {
                        Skin.Visible = true;
                        RgbSkinColorContainer.Visible = false;
                    }

                    var color = strategy.FromUnary(Skin.Value);

                    Markings.CurrentSkinColor = color;
                    Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));

                    break;
                }
                case SkinColorationStrategyInput.Color:
                {
                    if (!RgbSkinColorContainer.Visible)
                    {
                        Skin.Visible = false;
                        RgbSkinColorContainer.Visible = true;
                    }

                    var color = strategy.ClosestSkinColor(_rgbSkinColorSelector.Color);

                    Markings.CurrentSkinColor = color;
                    Profile = Profile.WithCharacterAppearance(Profile.Appearance.WithSkinColor(color));

                    break;
                }
            }

            ReloadProfilePreview();
        }

=======
>>>>>>> f92f9400ae31d5fd93e16a58e6257a15a51f220e
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

<<<<<<< HEAD
        protected override void ExitedTree()
        {
            base.ExitedTree();
            _entManager.DeleteEntity(PreviewDummy);
            PreviewDummy = EntityUid.Invalid;
        }

        private void SetAge(int newAge)
        {
            Profile = Profile?.WithAge(newAge);
            ReloadPreview();
        }

        private void SetSex(Sex newSex)
        {
            Profile = Profile?.WithSex(newSex);
            // for convenience, default to most common gender when new sex is selected
            switch (newSex)
            {
                case Sex.Male:
                    Profile = Profile?.WithGender(Gender.Male);
                    break;
                case Sex.Female:
                    Profile = Profile?.WithGender(Gender.Female);
                    break;
                default:
                    Profile = Profile?.WithGender(Gender.Epicene);
                    break;
            }

            UpdateGenderControls();
            UpdateTTSVoicesControls(); // Corvax-TTS
            Markings.SetSex(newSex);
            ReloadPreview();
        }

        private void SetGender(Gender newGender)
        {
            Profile = Profile?.WithGender(newGender);
            ReloadPreview();
        }

        // Corvax-TTS-Start
        private void SetVoice(string newVoice)
        {
            Profile = Profile?.WithVoice(newVoice);
            IsDirty = true;
        }
        // Corvax-TTS-End

        private void SetSpecies(string newSpecies)
        {
            Profile = Profile?.WithSpecies(newSpecies);
            OnSkinColorOnValueChanged(); // Species may have special color prefs, make sure to update it.
            Markings.SetSpecies(newSpecies); // Repopulate the markings tab as well.
            // In case there's job restrictions for the species
            RefreshJobs();
            // In case there's species restrictions for loadouts
            RefreshLoadouts();
            UpdateSexControls(); // update sex for new species
            UpdateSpeciesGuidebookIcon();
            ReloadPreview();
        }

        private void SetName(string newName)
        {
            Profile = Profile?.WithName(newName);
            SetDirty();

            if (!IsDirty)
                return;

            _entManager.System<MetaDataSystem>().SetEntityName(PreviewDummy, newName);
        }

        private void SetSpawnPriority(SpawnPriorityPreference newSpawnPriority)
        {
            Profile = Profile?.WithSpawnPriorityPreference(newSpawnPriority);
            SetDirty();
        }

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        private void UpdateNameEdit()
        {
            NameEdit.Text = Profile?.Name ?? "";
        }

        private void UpdateFlavorTextEdit()
        {
            if (_flavorTextEdit != null)
            {
                _flavorTextEdit.TextRope = new Rope.Leaf(Profile?.FlavorText ?? "");
            }
        }

        private void UpdateAgeEdit()
        {
            AgeEdit.Text = Profile?.Age.ToString() ?? "";
        }

        private void UpdateFactionControls()
        {
            if (Profile == null)
                return;

            FactionNameEdit.Text = Profile.FactionName;
            FactionDescEdit.Text = Profile.FactionDescription;
            FactionColorEdit.Text = Profile.FactionColor;
            FactionIconEdit.Text = Profile.FactionIcon;
            FactionRecruitingCheck.Pressed = Profile.FactionRecruiting;

            // Load Logo editor drawing state
            _factionBgColor = Profile.FactionLogoBackground;
            if (Profile.FactionLogo16 != null && Profile.FactionLogo16.Count == 16 * 16)
                Profile.FactionLogo16.CopyTo(_factionPixels);
            else
                Array.Clear(_factionPixels, 0, _factionPixels.Length);

            if (Profile.FactionLogo8 != null && Profile.FactionLogo8.Count == 8 * 8)
                Profile.FactionLogo8.CopyTo(_factionPixels8x8);
            else
                Array.Clear(_factionPixels8x8, 0, _factionPixels8x8.Length);

            UpdateFactionLogoPreviews();
            RefreshAllFactionLogoVisuals();

            // Load Filter controls
            int genderIdx = Profile.FactionFilterGender switch
            {
                "Male" => 1,
                "Female" => 2,
                "Unsexed" => 3,
                _ => 0
            };
            FactionFilterGenderOption.SelectId(genderIdx);
            FactionFilterNameEdit.Text = Profile.FactionFilterName;

            UpdateFactionFilterSpeciesUI();

            // Load Roles UI
            _selectedFactionRoleName = null;
            UpdateFactionRolesUI();
        }

        /// <summary>
        /// Updates selected job priorities to the profile's.
        /// </summary>
        private void UpdateJobPriorities()
        {
            foreach (var (jobId, prioritySelector) in _jobPriorities)
            {
                var priority = Profile?.JobPriorities.GetValueOrDefault(jobId, JobPriority.Never) ?? JobPriority.Never;
                prioritySelector.Select((int) priority);
            }
        }

        private void UpdateSexControls()
        {
            if (Profile == null)
                return;

            SexButton.Clear();

            var sexes = new List<Sex>();

            // add species sex options, default to just none if we are in bizzaro world and have no species
            if (_prototypeManager.Resolve<SpeciesPrototype>(Profile.Species, out var speciesProto))
            {
                foreach (var sex in speciesProto.Sexes)
                {
                    sexes.Add(sex);
                }
            }
            else
            {
                sexes.Add(Sex.Unsexed);
            }

            // add button for each sex
            foreach (var sex in sexes)
            {
                SexButton.AddItem(Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLower()}-text"), (int) sex);
            }

            if (sexes.Contains(Profile.Sex))
                SexButton.SelectId((int) Profile.Sex);
            else
                SexButton.SelectId((int) sexes[0]);
        }

        private void UpdateSkinColor()
        {
            if (Profile == null)
                return;

            var skin = _prototypeManager.Index<SpeciesPrototype>(Profile.Species).SkinColoration;
            var strategy = _prototypeManager.Index(skin).Strategy;

            switch (strategy.InputType)
            {
                case SkinColorationStrategyInput.Unary:
                {
                    if (!Skin.Visible)
                    {
                        Skin.Visible = true;
                        RgbSkinColorContainer.Visible = false;
                    }

                    Skin.Value = strategy.ToUnary(Profile.Appearance.SkinColor);

                    break;
                }
                case SkinColorationStrategyInput.Color:
                {
                    if (!RgbSkinColorContainer.Visible)
                    {
                        Skin.Visible = false;
                        RgbSkinColorContainer.Visible = true;
                    }

                    _rgbSkinColorSelector.Color = strategy.ClosestSkinColor(Profile.Appearance.SkinColor);

                    break;
                }
            }
        }

        public void UpdateSpeciesGuidebookIcon()
        {
            SpeciesInfoButton.StyleClasses.Clear();

            var species = Profile?.Species;
            if (species is null)
                return;

            if (!_prototypeManager.Resolve<SpeciesPrototype>(species, out var speciesProto))
                return;

            // Don't display the info button if no guide entry is found
            if (!_prototypeManager.HasIndex<GuideEntryPrototype>(species))
                return;

            const string style = "SpeciesInfoDefault";
            SpeciesInfoButton.StyleIdentifier = style;
        }

        private void UpdateMarkings()
        {
            if (Profile == null)
            {
                return;
            }

            Markings.SetData(Profile.Appearance.Markings, Profile.Species,
                Profile.Sex, Profile.Appearance.SkinColor, Profile.Appearance.EyeColor
            );
        }

        private void UpdateGenderControls()
        {
            if (Profile == null)
            {
                return;
            }

            PronounsButton.SelectId((int) Profile.Gender);
        }

        private void UpdateSpawnPriorityControls()
        {
            if (Profile == null)
            {
                return;
            }

            SpawnPriorityButton.SelectId((int) Profile.SpawnPriority);
        }

        private void UpdateHairPickers()
        {
            if (Profile == null)
            {
                return;
            }
            var hairMarking = Profile.Appearance.HairStyleId == HairStyles.DefaultHairStyle
                ? new List<Marking>()
                : new() { new(Profile.Appearance.HairStyleId, new List<Color>() { Profile.Appearance.HairColor }) };

            var facialHairMarking = Profile.Appearance.FacialHairStyleId == HairStyles.DefaultFacialHairStyle
                ? new List<Marking>()
                : new() { new(Profile.Appearance.FacialHairStyleId, new List<Color>() { Profile.Appearance.FacialHairColor }) };

            HairStylePicker.UpdateData(
                hairMarking,
                Profile.Species,
                1);
            FacialHairPicker.UpdateData(
                facialHairMarking,
                Profile.Species,
                1);
        }

        private void UpdateCMarkingsHair()
        {
            if (Profile == null)
            {
                return;
            }

            // hair color
            Color? hairColor = null;
            if ( Profile.Appearance.HairStyleId != HairStyles.DefaultHairStyle &&
                _markingManager.Markings.TryGetValue(Profile.Appearance.HairStyleId, out var hairProto)
            )
            {
                if (_markingManager.CanBeApplied(Profile.Species, Profile.Sex, hairProto, _prototypeManager))
                {
                    if (_markingManager.MustMatchSkin(Profile.Species, HumanoidVisualLayers.Hair, out var _, _prototypeManager))
                    {
                        hairColor = Profile.Appearance.SkinColor;
                    }
                    else
                    {
                        hairColor = Profile.Appearance.HairColor;
                    }
                }
            }
            if (hairColor != null)
            {
                Markings.HairMarking = new (Profile.Appearance.HairStyleId, new List<Color>() { hairColor.Value });
            }
            else
            {
                Markings.HairMarking = null;
            }
        }

        private void UpdateCMarkingsFacialHair()
        {
            if (Profile == null)
            {
                return;
            }

            // facial hair color
            Color? facialHairColor = null;
            if ( Profile.Appearance.FacialHairStyleId != HairStyles.DefaultFacialHairStyle &&
                _markingManager.Markings.TryGetValue(Profile.Appearance.FacialHairStyleId, out var facialHairProto))
            {
                if (_markingManager.CanBeApplied(Profile.Species, Profile.Sex, facialHairProto, _prototypeManager))
                {
                    if (_markingManager.MustMatchSkin(Profile.Species, HumanoidVisualLayers.Hair, out var _, _prototypeManager))
                    {
                        facialHairColor = Profile.Appearance.SkinColor;
                    }
                    else
                    {
                        facialHairColor = Profile.Appearance.FacialHairColor;
                    }
                }
            }
            if (facialHairColor != null)
            {
                Markings.FacialHairMarking = new (Profile.Appearance.FacialHairStyleId, new List<Color>() { facialHairColor.Value });
            }
            else
            {
                Markings.FacialHairMarking = null;
            }
        }

        private void UpdateEyePickers()
        {
            if (Profile == null)
            {
                return;
            }

            Markings.CurrentEyeColor = Profile.Appearance.EyeColor;
            EyeColorPicker.SetData(Profile.Appearance.EyeColor);
        }

=======
>>>>>>> f92f9400ae31d5fd93e16a58e6257a15a51f220e
        private void UpdateSaveButton()
        {
            SaveButton.Disabled = Profile is null || !IsDirty;
            ResetButton.Disabled = Profile is null || !IsDirty;
        }

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction)((int)direction % 4 * 2);
        }

        #region Faction Nested Editor Helpers
        private void InitializeFactionLogoEditor()
        {
            FactionLogoPixelGrid.DisposeAllChildren();
            for (int i = 0; i < 16 * 16; i++)
            {
                _factionPixels[i] = Color.Transparent;
                var panel = CreateFactionPixelPanel(i, 16);
                _factionPixelPanels[i] = panel;
                FactionLogoPixelGrid.AddChild(panel);
                UpdateFactionPixelVisual(i, 16);
            }

            FactionLogoPixelGrid8x8.DisposeAllChildren();
            for (int i = 0; i < 8 * 8; i++)
            {
                _factionPixels8x8[i] = Color.Transparent;
                var panel = CreateFactionPixelPanel(i, 8);
                _factionPixelPanels8x8[i] = panel;
                FactionLogoPixelGrid8x8.AddChild(panel);
                UpdateFactionPixelVisual(i, 8);
            }

            FactionLogoBgColorButton.OnPressed += _ =>
            {
                _factionBgColor = FactionLogoColorSelector.Color;
                UpdateFactionLogoPreviews();
                RefreshAllFactionLogoVisuals();
                UpdateFactionLogoProfile();
            };

            FactionLogoBrushColorButton.OnPressed += _ =>
            {
                _factionBrushColor = FactionLogoColorSelector.Color;
                FactionLogoEraserButton.Pressed = false;
                UpdateFactionLogoPreviews();
            };

            FactionLogoClearButton.OnPressed += _ =>
            {
                for (int i = 0; i < 16 * 16; i++) SetFactionPixel(i, Color.Transparent, 16);
                UpdateFactionLogoProfile();
            };

            FactionLogoClear8x8Button.OnPressed += _ =>
            {
                for (int i = 0; i < 8 * 8; i++) SetFactionPixel(i, Color.Transparent, 8);
                UpdateFactionLogoProfile();
            };

            UpdateFactionLogoPreviews();
            PopulateFactionLogoPresets();
        }

        private PanelContainer CreateFactionPixelPanel(int index, int size)
        {
            float pSize = size == 16 ? 16f : 12f;
            var panel = new PanelContainer
            {
                MinSize = new Vector2(pSize, pSize),
                MaxSize = new Vector2(pSize, pSize),
                MouseFilter = MouseFilterMode.Stop
            };

            panel.OnKeyBindDown += args =>
            {
                if (args.Function == EngineKeyFunctions.UIClick)
                {
                    _factionIsDrawing = true;
                    SetFactionPixel(index, FactionLogoEraserButton.Pressed ? Color.Transparent : _factionBrushColor, size);
                    UpdateFactionLogoProfile();
                }
                else if (args.Function == EngineKeyFunctions.UIRightClick)
                {
                    _factionIsRightDrawing = true;
                    SetFactionPixel(index, Color.Transparent, size);
                    UpdateFactionLogoProfile();
                }
            };

            panel.OnKeyBindUp += args =>
            {
                if (args.Function == EngineKeyFunctions.UIClick) _factionIsDrawing = false;
                else if (args.Function == EngineKeyFunctions.UIRightClick) _factionIsRightDrawing = false;
            };

            panel.OnMouseEntered += _ =>
            {
                if (_factionIsDrawing)
                {
                    SetFactionPixel(index, FactionLogoEraserButton.Pressed ? Color.Transparent : _factionBrushColor, size);
                    UpdateFactionLogoProfile();
                }
                else if (_factionIsRightDrawing)
                {
                    SetFactionPixel(index, Color.Transparent, size);
                    UpdateFactionLogoProfile();
                }
            };

            return panel;
        }

        private void UpdateFactionLogoPreviews()
        {
            if (FactionLogoBrushPreview.PanelOverride is StyleBoxFlat brushStyle) brushStyle.BackgroundColor = _factionBrushColor;
            if (FactionLogoBgPreview.PanelOverride is StyleBoxFlat bgStyle) bgStyle.BackgroundColor = _factionBgColor;
        }

        private void RefreshAllFactionLogoVisuals()
        {
            for (int i = 0; i < 16 * 16; i++) UpdateFactionPixelVisual(i, 16);
            for (int i = 0; i < 8 * 8; i++) UpdateFactionPixelVisual(i, 8);
        }

        private void SetFactionPixel(int index, Color color, int size)
        {
            if (size == 16) _factionPixels[index] = color;
            else _factionPixels8x8[index] = color;
            UpdateFactionPixelVisual(index, size);
        }

        private void UpdateFactionPixelVisual(int index, int size)
        {
            var pixels = size == 16 ? _factionPixels : _factionPixels8x8;
            var panels = size == 16 ? _factionPixelPanels : _factionPixelPanels8x8;

            var color = pixels[index] == Color.Transparent ? _factionBgColor : pixels[index];
            if (color == Color.Transparent)
            {
                bool isDark = ((index % size) + (index / size)) % 2 == 0;
                color = isDark ? new Color(35, 35, 35) : new Color(25, 25, 25);
            }

            panels[index].PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = color,
                BorderColor = new Color(50, 50, 50, 40),
                BorderThickness = new Thickness(1)
            };
        }

        private void PopulateFactionLogoPresets()
        {
            var prototypeManager = IoCManager.Resolve<IPrototypeManager>();
            var resourceManager = IoCManager.Resolve<IResourceManager>();
            var resourceCache = IoCManager.Resolve<IResourceCache>();

            FactionLogoPresetGrid.DisposeAllChildren();

            foreach (var preset in prototypeManager.EnumeratePrototypes<FactionLogoPresetPrototype>())
            {
                var folderName = preset.SpriteFolder.Filename;

                ResPath? file16 = null;
                var path16 = preset.SpriteFolder / $"{folderName}.png";
                var path16Alt = preset.SpriteFolder / $"{folderName}_16.png";

                if (resourceManager.ContentFileExists(path16))
                    file16 = path16;
                else if (resourceManager.ContentFileExists(path16Alt))
                    file16 = path16Alt;

                ResPath? file8 = null;
                var path8 = preset.SpriteFolder / $"{folderName}_8x8.png";
                var path8Alt = preset.SpriteFolder / $"{folderName}_8.png";

                if (resourceManager.ContentFileExists(path8))
                    file8 = path8;
                else if (resourceManager.ContentFileExists(path8Alt))
                    file8 = path8Alt;

                if (file16 == null || file8 == null)
                    continue;

                var pixels16 = LoadFactionPixelsFromTexture(resourceCache, file16.Value, 16);
                var pixels8 = LoadFactionPixelsFromTexture(resourceCache, file8.Value, 8);

                AddFactionPresetButton(Loc.GetString(preset.Name), pixels16, pixels8);
            }
        }

        private List<Color> LoadFactionPixelsFromTexture(IResourceCache cache, ResPath path, int expectedSize)
        {
            var result = new List<Color>(expectedSize * expectedSize);
            var texture = cache.GetResource<TextureResource>(path).Texture;

            int width = Math.Min(texture.Width, expectedSize);
            int height = Math.Min(texture.Height, expectedSize);

            for (int y = 0; y < expectedSize; y++)
            {
                for (int x = 0; x < expectedSize; x++)
                {
                    if (x < width && y < height)
                    {
                        var p = texture.GetPixel(x, y);
                        if (p.A == 0)
                        {
                            result.Add(Color.Transparent);
                        }
                        else
                        {
                            result.Add(Color.White);
                        }
                    }
                    else
                    {
                        result.Add(Color.Transparent);
                    }
                }
            }

            return result;
        }

        private void AddFactionPresetButton(string name, List<Color> pixels16, List<Color> pixels8)
        {
            var button = new Button
            {
                MinSize = new Vector2(36, 36),
                ToolTip = name,
            };

            var logoControl = new FactionLogoControl
            {
                MinSize = new Vector2(24, 24),
                MaxSize = new Vector2(24, 24),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                MouseFilter = MouseFilterMode.Ignore
            };
            logoControl.UpdateLogo(Color.Transparent, pixels16);

            button.AddChild(logoControl);
            button.OnPressed += _ =>
            {
                ApplyFactionPreset(pixels16, pixels8);
                UpdateFactionLogoProfile();
            };

            FactionLogoPresetGrid.AddChild(button);
        }

        private void ApplyFactionPreset(List<Color> pixels16, List<Color> pixels8)
        {
            for (int i = 0; i < 16 * 16; i++)
            {
                _factionPixels[i] = pixels16[i] != Color.Transparent ? _factionBrushColor : Color.Transparent;
            }

            for (int i = 0; i < 8 * 8; i++)
            {
                _factionPixels8x8[i] = pixels8[i] != Color.Transparent ? _factionBrushColor : Color.Transparent;
            }

            RefreshAllFactionLogoVisuals();
        }

        private void UpdateFactionLogoProfile()
        {
            Profile = Profile?.WithFactionLogo16(_factionPixels.ToList())
                              .WithFactionLogo8(_factionPixels8x8.ToList())
                              .WithFactionLogoBackground(_factionBgColor);
            IsDirty = true;
        }

        private void InitializeFactionRolesEditor()
        {
            FactionRoleAddButton.OnPressed += _ =>
            {
                var roleName = FactionRoleNameEdit.Text.Trim();
                if (string.IsNullOrWhiteSpace(roleName))
                    return;

                if (Profile == null)
                    return;

                if (Profile.FactionRoles.Any(r => string.Equals(r.Name, roleName, StringComparison.OrdinalIgnoreCase)))
                    return;

                var newRole = new FactionRole
                {
                    Name = roleName,
                    CanInvite = FactionRoleInviteCheck.Pressed,
                    CanResearch = FactionRoleResearchCheck.Pressed,
                    CanManageRoles = FactionRoleManageCheck.Pressed,
                    CanInherit = FactionRoleInheritCheck.Pressed
                };

                var newList = new List<FactionRole>(Profile.FactionRoles) { newRole };
                Profile = Profile.WithFactionRoles(newList);
                IsDirty = true;

                FactionRoleNameEdit.Text = string.Empty;
                UpdateFactionRolesUI();
            };

            FactionRoleRemoveButton.OnPressed += _ =>
            {
                if (Profile == null || string.IsNullOrEmpty(_selectedFactionRoleName))
                    return;

                var newList = Profile.FactionRoles.Where(r => r.Name != _selectedFactionRoleName).ToList();
                Profile = Profile.WithFactionRoles(newList);
                IsDirty = true;
                _selectedFactionRoleName = null;

                UpdateFactionRolesUI();
            };
        }

        private void UpdateFactionRolesUI()
        {
            FactionRolesListContainer.DisposeAllChildren();
            if (Profile == null)
                return;

            foreach (var role in Profile.FactionRoles)
            {
                var roleButton = new Button
                {
                    Text = role.Name,
                    ToggleMode = true,
                    Pressed = role.Name == _selectedFactionRoleName,
                    HorizontalExpand = true
                };

                var captureRoleName = role.Name;
                roleButton.OnPressed += _ =>
                {
                    _selectedFactionRoleName = captureRoleName;
                    foreach (var child in FactionRolesListContainer.Children)
                    {
                        if (child is Button btn && btn.Text != captureRoleName)
                            btn.Pressed = false;
                    }

                    var r = Profile.FactionRoles.FirstOrDefault(x => x.Name == captureRoleName);
                    if (r.Name != null)
                    {
                        FactionRoleNameEdit.Text = r.Name;
                        FactionRoleInviteCheck.Pressed = r.CanInvite;
                        FactionRoleResearchCheck.Pressed = r.CanResearch;
                        FactionRoleManageCheck.Pressed = r.CanManageRoles;
                        FactionRoleInheritCheck.Pressed = r.CanInherit;
                    }
                };

                FactionRolesListContainer.AddChild(roleButton);
            }
        }

        private void InitializeFactionFiltersEditor()
        {
            FactionFilterGenderOption.Clear();
            FactionFilterGenderOption.AddItem("Все", 0);
            FactionFilterGenderOption.AddItem("Мужской", 1);
            FactionFilterGenderOption.AddItem("Женский", 2);
            FactionFilterGenderOption.AddItem("Безполый", 3);

            FactionFilterGenderOption.OnItemSelected += args =>
            {
                FactionFilterGenderOption.SelectId(args.Id);
                string genderVal = args.Id switch
                {
                    1 => "Male",
                    2 => "Female",
                    3 => "Unsexed",
                    _ => "All"
                };
                Profile = Profile?.WithFactionFilterGender(genderVal);
                IsDirty = true;
            };

            FactionFilterNameEdit.OnTextChanged += args =>
            {
                Profile = Profile?.WithFactionFilterName(args.Text);
                IsDirty = true;
            };

            UpdateFactionFilterSpeciesUI();
        }

        private void UpdateFactionFilterSpeciesUI()
        {
            FactionFilterSpeciesList.DisposeAllChildren();
            if (Profile == null)
                return;

            foreach (var species in _prototypeManager.EnumeratePrototypes<SpeciesPrototype>())
            {
                var speciesId = species.ID;
                var checkBox = new CheckBox
                {
                    Text = Loc.GetString(species.Name),
                    Pressed = Profile.FactionFilterSpecies.Contains(speciesId)
                };

                checkBox.OnToggled += args =>
                {
                    if (Profile == null)
                        return;

                    var currentList = new List<string>(Profile.FactionFilterSpecies);
                    if (args.Pressed)
                    {
                        if (!currentList.Contains(speciesId))
                            currentList.Add(speciesId);
                    }
                    else
                    {
                        currentList.Remove(speciesId);
                    }

                    Profile = Profile.WithFactionFilterSpecies(currentList);
                    IsDirty = true;
                };

                FactionFilterSpeciesList.AddChild(checkBox);
            }
        }
        #endregion
    }
}
