using Content.Client.Humanoid;
using Content.Client.Message;
using Content.Client.Players.PlayTimeTracking;
using Content.Client.Sprite;
using Content.Shared.CCVar;
using Content.Shared.GameTicking;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Configuration;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.Maths;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;
using Direction = Robust.Shared.Maths.Direction;
using static Content.Client.Corvax.SponsorOnlyHelpers; // Corvax-Sponsors
using Content.Client.Corvax.TTS; // Corvax-TTS
using Content.Shared._Nibiru.Factions;
using Content.Client.UserInterface.Systems.Faction.UI;
using Robust.Client.ResourceManagement;
using Robust.Shared.Input;
using Robust.Shared.Utility;
using System.Linq;
using Content.Shared.FixedPoint;
using Robust.Client.Graphics;
using System.Numerics;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HumanoidProfileEditor : BoxContainer
    {
        private readonly IClientPreferencesManager _preferencesManager;
        private readonly IConfigurationManager _cfgManager;
        private readonly IEntityManager _entManager;
        private readonly IFileDialogManager _dialogManager;
        private readonly IPlayerManager _playerManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly IResourceManager _resManager;
        private readonly MarkingManager _markingManager;
        private readonly JobRequirementsManager _requirements;
        private readonly LobbyUIController _controller;

        private readonly SpriteSystem _sprite;

        // CCvar.
        private int _maxNameLength;

        /// <summary>
        /// If we're attempting to save.
        /// </summary>
        public event Action? Save;

        /// <summary>
        /// The character slot for the current profile.
        /// </summary>
        public int? CharacterSlot;

        /// <summary>
        /// The work in progress profile being edited.
        /// </summary>
        public HumanoidCharacterProfile? Profile;

        private Direction _previewRotation = Direction.North;

        private Color _factionBrushColor = Color.White;
        private Color _factionBgColor = Color.Transparent;
        private Color[] _factionPixels = new Color[16 * 16];
        private PanelContainer[] _factionPixelPanels = new PanelContainer[16 * 16];
        private Color[] _factionPixels8x8 = new Color[8 * 8];
        private PanelContainer[] _factionPixelPanels8x8 = new PanelContainer[8 * 8];
        private bool _factionIsDrawing = false;
        private bool _factionIsRightDrawing = false;
        private string? _selectedFactionRoleName = null;
        private bool _isDirty;

        public bool IsDirty
        {
            get => _isDirty;
            set
            {
                if (_isDirty == value)
                    return;

                _isDirty = value;
                UpdateSaveButton();
            }
        }

        private ISawmill _sawmill;

        private MarkingsViewModel _markingsModel = new();

        public HumanoidProfileEditor(
            IClientPreferencesManager preferencesManager,
            IConfigurationManager configurationManager,
            IEntityManager entManager,
            IFileDialogManager dialogManager,
            ILogManager logManager,
            IPlayerManager playerManager,
            IPrototypeManager prototypeManager,
            IResourceManager resManager,
            JobRequirementsManager requirements,
            MarkingManager markings)
        {
            RobustXamlLoader.Load(this);
            _sawmill = logManager.GetSawmill("profile.editor");
            _cfgManager = configurationManager;
            _entManager = entManager;
            _dialogManager = dialogManager;
            _playerManager = playerManager;
            _prototypeManager = prototypeManager;
            _markingManager = markings;
            _preferencesManager = preferencesManager;
            _resManager = resManager;
            _requirements = requirements;
            _controller = UserInterfaceManager.GetUIController<LobbyUIController>();
            _sprite = _entManager.System<SpriteSystem>();

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _allowFlavorText = _cfgManager.GetCVar(CCVars.FlavorText);

            Markings.SetModel(_markingsModel);

            ImportButton.OnPressed += args =>
            {
                ImportProfile();
            };

            ExportButton.OnPressed += args =>
            {
                ExportProfile();
            };

            ExportImageButton.OnPressed += args =>
            {
                ExportImage();
            };

            OpenImagesButton.OnPressed += args =>
            {
                _resManager.UserData.OpenOsWindow(ContentSpriteSystem.Exports);
            };

            ResetButton.OnPressed += args =>
            {
                SetProfile((HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter, _preferencesManager.Preferences?.SelectedCharacterIndex);
            };

            SaveButton.OnPressed += args =>
            {
                Save?.Invoke();
            };

            #region Left

            #region Name

            NameEdit.OnTextChanged += args => { SetName(args.Text); };
            NameEdit.IsValid = args => args.Length <= _maxNameLength;
            NameRandomize.OnPressed += args => RandomizeName();
            RandomizeEverythingButton.OnPressed += args => { RandomizeEverything(); };
            WarningLabel.SetMarkup($"[color=red]{Loc.GetString("humanoid-profile-editor-naming-rules-warning")}[/color]");

            #endregion Name

            #region Appearance

            TabContainer.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-appearance-tab"));

            #region Sex

            SexButton.OnItemSelected += args =>
            {
                SexButton.SelectId(args.Id);
                SetSex((Sex)args.Id);
            };

            #endregion Sex

            #region Age

            AgeEdit.OnTextChanged += args =>
            {
                if (!int.TryParse(args.Text, out var newAge))
                    return;

                SetAge(newAge);
            };

            #endregion Age

            #region Gender

            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int)Gender.Male);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int)Gender.Female);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int)Gender.Epicene);
            PronounsButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int)Gender.Neuter);

            PronounsButton.OnItemSelected += args =>
            {
                PronounsButton.SelectId(args.Id);
                SetGender((Gender)args.Id);
            };

            #endregion Gender

            RefreshSpecies();

            SpeciesButton.OnItemSelected += args =>
            {
                SpeciesButton.SelectId(args.Id);
                SetSpecies(_species[args.Id].ID);
                OnSkinColorOnValueChanged();
            };

            #region Skin

            Skin.OnValueChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            RgbSkinColorContainer.AddChild(_rgbSkinColorSelector = new ColorSelectorSliders());
            _rgbSkinColorSelector.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv; // defaults color selector to HSV
            _rgbSkinColorSelector.OnColorChanged += _ =>
            {
                OnSkinColorOnValueChanged();
            };

            #endregion

            #region SpawnPriority

            foreach (var value in Enum.GetValues<SpawnPriorityPreference>())
            {
                SpawnPriorityButton.AddItem(Loc.GetString($"humanoid-profile-editor-preference-spawn-priority-{value.ToString().ToLower()}"), (int)value);
            }

            SpawnPriorityButton.OnItemSelected += args =>
            {
                SpawnPriorityButton.SelectId(args.Id);
                SetSpawnPriority((SpawnPriorityPreference)args.Id);
            };

            #endregion SpawnPriority

            #region Eyes

            EyeColorPicker.OnEyeColorPicked += newColor =>
            {
                if (Profile is null)
                    return;
                Profile = Profile.WithCharacterAppearance(
                    Profile.Appearance.WithEyeColor(newColor));
                _markingsModel.SetOrganEyeColor(Profile.Appearance.EyeColor);
                ReloadProfilePreview();
            };

            #endregion Eyes

            #endregion Appearance

            #region Jobs

            // TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-jobs-tab"));

            /*
            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-stay-in-lobby-button"),
                (int)PreferenceUnavailableMode.StayInLobby);
            PreferenceUnavailableButton.AddItem(
                Loc.GetString("humanoid-profile-editor-preference-unavailable-spawn-as-overflow-button",
                              ("overflowJob", Loc.GetString(SharedGameTicker.FallbackOverflowJobName))),
                (int)PreferenceUnavailableMode.SpawnAsOverflow);

            PreferenceUnavailableButton.OnItemSelected += args =>
            {
                PreferenceUnavailableButton.SelectId(args.Id);
                Profile = Profile?.WithPreferenceUnavailable((PreferenceUnavailableMode)args.Id);
                SetDirty();
            };
            */

            _jobCategories = new Dictionary<string, BoxContainer>();

            // RefreshAntags();
            // RefreshJobs();

            #endregion Jobs

            // TabContainer.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-antags-tab"));

            RefreshTraits();

            TabContainer.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-traits-tab")); // Corvax-TTS-Edit

            #region Markings

            TabContainer.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-markings-tab"));

            _markingsModel.MarkingsChanged += (_, _) => OnMarkingChange();
            _markingsModel.MarkingsReset += OnMarkingChange;

            #endregion Markings

            #region Factions
            TabContainer.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-faction-tab"));

            FactionSubTabs.SetTabTitle(0, Loc.GetString("humanoid-profile-editor-faction-subtab-main"));
            FactionSubTabs.SetTabTitle(1, Loc.GetString("humanoid-profile-editor-faction-subtab-logo"));
            FactionSubTabs.SetTabTitle(2, Loc.GetString("humanoid-profile-editor-faction-subtab-roles"));
            FactionSubTabs.SetTabTitle(3, Loc.GetString("humanoid-profile-editor-faction-subtab-filters"));

            FactionNameEdit.OnTextChanged += args => { Profile = Profile?.WithFactionName(args.Text); IsDirty = true; };
            FactionDescEdit.OnTextChanged += args => { Profile = Profile?.WithFactionDescription(args.Text); IsDirty = true; };
            FactionColorEdit.OnTextChanged += args => { Profile = Profile?.WithFactionColor(args.Text); IsDirty = true; };
            FactionIconEdit.OnTextChanged += args => { Profile = Profile?.WithFactionIcon(args.Text); IsDirty = true; };
            FactionRecruitingCheck.OnToggled += args => { Profile = Profile?.WithFactionRecruiting(args.Pressed); IsDirty = true; };

            InitializeFactionLogoEditor();
            InitializeFactionRolesEditor();
            InitializeFactionFiltersEditor();
            #endregion Factions

            RefreshFlavorText();

            RefreshVoiceTab(); // Corvax-TTS

            #region Dummy

            SpriteRotateLeft.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCw();
                SetPreviewRotation(_previewRotation);
            };
            SpriteRotateRight.OnPressed += _ =>
            {
                _previewRotation = _previewRotation.TurnCcw();
                SetPreviewRotation(_previewRotation);
            };

            #endregion Dummy

            #endregion Left

            ShowClothes.OnToggled += args =>
            {
                ReloadPreview();
            };

            SpeciesInfoButton.OnPressed += OnSpeciesInfoButtonPressed;

            UpdateSpeciesGuidebookIcon();
            IsDirty = false;
        }

        private void SetDirty()
        {
            // If it equals default then reset the button.
            if (Profile == null || _preferencesManager.Preferences?.SelectedCharacter.MemberwiseEquals(Profile) == true)
            {
                IsDirty = false;
                return;
            }

            // TODO: Check if profile matches default.
            IsDirty = true;
        }

        /// <summary>
        /// Reloads the entire dummy entity for preview.
        /// </summary>
        /// <remarks>
        /// This is expensive so not recommended to run if you have a slider.
        /// </remarks>
        private void ReloadPreview()
        {
            if (Profile == null)
                return;

            SpriteView.LoadPreview(Profile, JobOverride, ShowClothes.Pressed);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        /// <summary>
        /// Resets the profile to the defaults.
        /// </summary>
        public void ResetToDefault()
        {
            SetProfile(
                (HumanoidCharacterProfile?)_preferencesManager.Preferences?.SelectedCharacter,
                _preferencesManager.Preferences?.SelectedCharacterIndex);
        }

        /// <summary>
        /// Sets the editor to the specified profile with the specified slot.
        /// </summary>
        public void SetProfile(HumanoidCharacterProfile? profile, int? slot)
        {
            Profile = profile?.Clone();
            CharacterSlot = slot;
            IsDirty = false;
            JobOverride = null;

            UpdateNameEdit();
            UpdateFlavorTextEdit();
            UpdateSexControls();
            UpdateGenderControls();
            UpdateSkinColor();
            UpdateSpawnPriorityControls();
            UpdateAgeEdit();
            UpdateEyePickers();
            UpdateSaveButton();
            UpdateMarkings();
            UpdateTTSVoicesControls(); // Corvax-TTS

            // RefreshAntags();
            // RefreshJobs();
            RefreshLoadouts();
            RefreshSpecies();
            RefreshTraits();
            RefreshFlavorText();
            ReloadPreview();

            /*
            if (Profile != null)
            {
                PreferenceUnavailableButton.SelectId((int)Profile.PreferenceUnavailable);
            }
            */
        }

        /// <summary>
        /// A slim reload that only updates the entity itself and not any of the job entities, etc.
        /// </summary>
        private void ReloadProfilePreview()
        {
            if (Profile == null)
                return;

            SpriteView.ReloadProfilePreview(Profile);

            // Check and set the dirty flag to enable the save/reset buttons as appropriate.
            SetDirty();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing)
                return;

            _loadoutWindow?.Dispose();
            _loadoutWindow = null;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            ReloadPreview();
        }

        private void UpdateSaveButton()
        {
            SaveButton.Disabled = Profile is null || !IsDirty;
            ResetButton.Disabled = Profile is null || !IsDirty;
        }

        private void SetPreviewRotation(Direction direction)
        {
            SpriteView.OverrideDirection = (Direction)((int)direction % 4 * 2);
        }

        #region Faction Nested Editor Helpers
        private void InitializeFactionLogoEditor()
        {
            FactionLogoPixelGrid.DisposeAllChildren();
            for (int i = 0; i < 16 * 16; i++)
            {
                _factionPixels[i] = Color.Transparent;
                var panel = CreateFactionPixelPanel(i, 16);
                _factionPixelPanels[i] = panel;
                FactionLogoPixelGrid.AddChild(panel);
                UpdateFactionPixelVisual(i, 16);
            }

            FactionLogoPixelGrid8x8.DisposeAllChildren();
            for (int i = 0; i < 8 * 8; i++)
            {
                _factionPixels8x8[i] = Color.Transparent;
                var panel = CreateFactionPixelPanel(i, 8);
                _factionPixelPanels8x8[i] = panel;
                FactionLogoPixelGrid8x8.AddChild(panel);
                UpdateFactionPixelVisual(i, 8);
            }

            FactionLogoBgColorButton.OnPressed += _ =>
            {
                _factionBgColor = FactionLogoColorSelector.Color;
                UpdateFactionLogoPreviews();
                RefreshAllFactionLogoVisuals();
                UpdateFactionLogoProfile();
            };

            FactionLogoBrushColorButton.OnPressed += _ =>
            {
                _factionBrushColor = FactionLogoColorSelector.Color;
                FactionLogoEraserButton.Pressed = false;
                UpdateFactionLogoPreviews();
            };

            FactionLogoClearButton.OnPressed += _ =>
            {
                for (int i = 0; i < 16 * 16; i++) SetFactionPixel(i, Color.Transparent, 16);
                UpdateFactionLogoProfile();
            };

            FactionLogoClear8x8Button.OnPressed += _ =>
            {
                for (int i = 0; i < 8 * 8; i++) SetFactionPixel(i, Color.Transparent, 8);
                UpdateFactionLogoProfile();
            };

            UpdateFactionLogoPreviews();
            PopulateFactionLogoPresets();
        }

        private PanelContainer CreateFactionPixelPanel(int index, int size)
        {
            float pSize = size == 16 ? 16f : 12f;
            var panel = new PanelContainer
            {
                MinSize = new Vector2(pSize, pSize),
                MaxSize = new Vector2(pSize, pSize),
                MouseFilter = MouseFilterMode.Stop
            };

            panel.OnKeyBindDown += args =>
            {
                if (args.Function == EngineKeyFunctions.UIClick)
                {
                    _factionIsDrawing = true;
                    SetFactionPixel(index, FactionLogoEraserButton.Pressed ? Color.Transparent : _factionBrushColor, size);
                    UpdateFactionLogoProfile();
                }
                else if (args.Function == EngineKeyFunctions.UIRightClick)
                {
                    _factionIsRightDrawing = true;
                    SetFactionPixel(index, Color.Transparent, size);
                    UpdateFactionLogoProfile();
                }
            };

            panel.OnKeyBindUp += args =>
            {
                if (args.Function == EngineKeyFunctions.UIClick) _factionIsDrawing = false;
                else if (args.Function == EngineKeyFunctions.UIRightClick) _factionIsRightDrawing = false;
            };

            panel.OnMouseEntered += _ =>
            {
                if (_factionIsDrawing)
                {
                    SetFactionPixel(index, FactionLogoEraserButton.Pressed ? Color.Transparent : _factionBrushColor, size);
                    UpdateFactionLogoProfile();
                }
                else if (_factionIsRightDrawing)
                {
                    SetFactionPixel(index, Color.Transparent, size);
                    UpdateFactionLogoProfile();
                }
            };

            return panel;
        }

        private void UpdateFactionLogoPreviews()
        {
            if (FactionLogoBrushPreview.PanelOverride is StyleBoxFlat brushStyle) brushStyle.BackgroundColor = _factionBrushColor;
            if (FactionLogoBgPreview.PanelOverride is StyleBoxFlat bgStyle) bgStyle.BackgroundColor = _factionBgColor;
        }

        private void RefreshAllFactionLogoVisuals()
        {
            for (int i = 0; i < 16 * 16; i++) UpdateFactionPixelVisual(i, 16);
            for (int i = 0; i < 8 * 8; i++) UpdateFactionPixelVisual(i, 8);
        }

        private void SetFactionPixel(int index, Color color, int size)
        {
            if (size == 16) _factionPixels[index] = color;
            else _factionPixels8x8[index] = color;
            UpdateFactionPixelVisual(index, size);
        }

        private void UpdateFactionPixelVisual(int index, int size)
        {
            var pixels = size == 16 ? _factionPixels : _factionPixels8x8;
            var panels = size == 16 ? _factionPixelPanels : _factionPixelPanels8x8;

            var color = pixels[index] == Color.Transparent ? _factionBgColor : pixels[index];
            if (color == Color.Transparent)
            {
                bool isDark = ((index % size) + (index / size)) % 2 == 0;
                color = isDark ? new Color(35, 35, 35) : new Color(25, 25, 25);
            }

            panels[index].PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = color,
                BorderColor = new Color(50, 50, 50, 40),
                BorderThickness = new Thickness(1)
            };
        }

        private void PopulateFactionLogoPresets()
        {
            var prototypeManager = IoCManager.Resolve<IPrototypeManager>();
            var resourceManager = IoCManager.Resolve<IResourceManager>();
            var resourceCache = IoCManager.Resolve<IResourceCache>();

            FactionLogoPresetGrid.DisposeAllChildren();

            foreach (var preset in prototypeManager.EnumeratePrototypes<FactionLogoPresetPrototype>())
            {
                // Прямые пути к файлам или папка с конвенцией имён
                ResPath? file16 = preset.Sprite16;
                ResPath? file8 = preset.Sprite8;

                if (preset.SpriteFolder != null)
                {
                    var folder = preset.SpriteFolder.Value;
                    var folderName = folder.Filename;

                    file16 ??= TryResolveFile(resourceManager, folder / $"{folderName}.png");
                    file16 ??= TryResolveFile(resourceManager, folder / $"{folderName}_16.png");

                    file8 ??= TryResolveFile(resourceManager, folder / $"{folderName}_8x8.png");
                    file8 ??= TryResolveFile(resourceManager, folder / $"{folderName}_8.png");
                }

                if (file16 == null || file8 == null)
                    continue;

                var pixels16 = LoadFactionPixelsFromTexture(resourceCache, file16.Value, 16);
                var pixels8 = LoadFactionPixelsFromTexture(resourceCache, file8.Value, 8);

                AddFactionPresetButton(Loc.GetString(preset.Name), pixels16, pixels8);
            }
        }

        private static ResPath? TryResolveFile(IResourceManager resourceManager, ResPath path)
        {
            return resourceManager.ContentFileExists(path) ? path : null;
        }

        private List<Color> LoadFactionPixelsFromTexture(IResourceCache cache, ResPath path, int expectedSize)
        {
            var result = new List<Color>(expectedSize * expectedSize);
            var texture = cache.GetResource<TextureResource>(path).Texture;

            int width = Math.Min(texture.Width, expectedSize);
            int height = Math.Min(texture.Height, expectedSize);

            for (int y = 0; y < expectedSize; y++)
            {
                for (int x = 0; x < expectedSize; x++)
                {
                    if (x < width && y < height)
                    {
                        var p = texture.GetPixel(x, y);
                        if (p.A == 0)
                        {
                            result.Add(Color.Transparent);
                        }
                        else
                        {
                            result.Add(Color.White);
                        }
                    }
                    else
                    {
                        result.Add(Color.Transparent);
                    }
                }
            }

            return result;
        }

        private void AddFactionPresetButton(string name, List<Color> pixels16, List<Color> pixels8)
        {
            var button = new Button
            {
                MinSize = new Vector2(36, 36),
                ToolTip = name,
            };

            var logoControl = new FactionLogoControl
            {
                MinSize = new Vector2(24, 24),
                MaxSize = new Vector2(24, 24),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                MouseFilter = MouseFilterMode.Ignore
            };
            logoControl.UpdateLogo(Color.Transparent, pixels16);

            button.AddChild(logoControl);
            button.OnPressed += _ =>
            {
                ApplyFactionPreset(pixels16, pixels8);
                UpdateFactionLogoProfile();
            };

            FactionLogoPresetGrid.AddChild(button);
        }

        private void ApplyFactionPreset(List<Color> pixels16, List<Color> pixels8)
        {
            for (int i = 0; i < 16 * 16; i++)
            {
                _factionPixels[i] = pixels16[i] != Color.Transparent ? _factionBrushColor : Color.Transparent;
            }

            for (int i = 0; i < 8 * 8; i++)
            {
                _factionPixels8x8[i] = pixels8[i] != Color.Transparent ? _factionBrushColor : Color.Transparent;
            }

            RefreshAllFactionLogoVisuals();
        }

        private void UpdateFactionLogoProfile()
        {
            Profile = Profile?.WithFactionLogo16(_factionPixels.ToList())
                              .WithFactionLogo8(_factionPixels8x8.ToList())
                              .WithFactionLogoBackground(_factionBgColor);
            IsDirty = true;
        }

        private void InitializeFactionRolesEditor()
        {
            FactionRoleAddButton.OnPressed += _ =>
            {
                var roleName = FactionRoleNameEdit.Text.Trim();
                if (string.IsNullOrWhiteSpace(roleName))
                    return;

                if (Profile == null)
                    return;

                if (Profile.FactionRoles.Any(r => string.Equals(r.Name, roleName, StringComparison.OrdinalIgnoreCase)))
                    return;

                var newRole = new FactionRole
                {
                    Name = roleName,
                    CanInvite = FactionRoleInviteCheck.Pressed,
                    CanResearch = FactionRoleResearchCheck.Pressed,
                    CanManageRoles = FactionRoleManageCheck.Pressed,
                    CanInherit = FactionRoleInheritCheck.Pressed
                };

                var newList = new List<FactionRole>(Profile.FactionRoles) { newRole };
                Profile = Profile.WithFactionRoles(newList);
                IsDirty = true;

                FactionRoleNameEdit.Text = string.Empty;
                UpdateFactionRolesUI();
            };

            FactionRoleRemoveButton.OnPressed += _ =>
            {
                if (Profile == null || string.IsNullOrEmpty(_selectedFactionRoleName))
                    return;

                var newList = Profile.FactionRoles.Where(r => r.Name != _selectedFactionRoleName).ToList();
                Profile = Profile.WithFactionRoles(newList);
                IsDirty = true;
                _selectedFactionRoleName = null;

                UpdateFactionRolesUI();
            };
        }

        private void UpdateFactionRolesUI()
        {
            FactionRolesListContainer.DisposeAllChildren();
            if (Profile == null)
                return;

            foreach (var role in Profile.FactionRoles)
            {
                var roleButton = new Button
                {
                    Text = role.Name,
                    ToggleMode = true,
                    Pressed = role.Name == _selectedFactionRoleName,
                    HorizontalExpand = true
                };

                var captureRoleName = role.Name;
                roleButton.OnPressed += _ =>
                {
                    _selectedFactionRoleName = captureRoleName;
                    foreach (var child in FactionRolesListContainer.Children)
                    {
                        if (child is Button btn && btn.Text != captureRoleName)
                            btn.Pressed = false;
                    }

                    var r = Profile.FactionRoles.FirstOrDefault(x => x.Name == captureRoleName);
                    if (r.Name != null)
                    {
                        FactionRoleNameEdit.Text = r.Name;
                        FactionRoleInviteCheck.Pressed = r.CanInvite;
                        FactionRoleResearchCheck.Pressed = r.CanResearch;
                        FactionRoleManageCheck.Pressed = r.CanManageRoles;
                        FactionRoleInheritCheck.Pressed = r.CanInherit;
                    }
                };

                FactionRolesListContainer.AddChild(roleButton);
            }
        }

        private void InitializeFactionFiltersEditor()
        {
            FactionFilterGenderOption.Clear();
            FactionFilterGenderOption.AddItem("Все", 0);
            FactionFilterGenderOption.AddItem("Мужской", 1);
            FactionFilterGenderOption.AddItem("Женский", 2);
            FactionFilterGenderOption.AddItem("Безполый", 3);

            FactionFilterGenderOption.OnItemSelected += args =>
            {
                FactionFilterGenderOption.SelectId(args.Id);
                string genderVal = args.Id switch
                {
                    1 => "Male",
                    2 => "Female",
                    3 => "Unsexed",
                    _ => "All"
                };
                Profile = Profile?.WithFactionFilterGender(genderVal);
                IsDirty = true;
            };

            FactionFilterNameEdit.OnTextChanged += args =>
            {
                Profile = Profile?.WithFactionFilterName(args.Text);
                IsDirty = true;
            };

            UpdateFactionFilterSpeciesUI();
        }

        private void UpdateFactionFilterSpeciesUI()
        {
            FactionFilterSpeciesList.DisposeAllChildren();
            if (Profile == null)
                return;

            foreach (var species in _prototypeManager.EnumeratePrototypes<SpeciesPrototype>())
            {
                var speciesId = species.ID;
                var checkBox = new CheckBox
                {
                    Text = Loc.GetString(species.Name),
                    Pressed = Profile.FactionFilterSpecies.Contains(speciesId)
                };

                checkBox.OnToggled += args =>
                {
                    if (Profile == null)
                        return;

                    var currentList = new List<string>(Profile.FactionFilterSpecies);
                    if (args.Pressed)
                    {
                        if (!currentList.Contains(speciesId))
                            currentList.Add(speciesId);
                    }
                    else
                    {
                        currentList.Remove(speciesId);
                    }

                    Profile = Profile.WithFactionFilterSpecies(currentList);
                    IsDirty = true;
                };

                FactionFilterSpeciesList.AddChild(checkBox);
            }
        }
        #endregion
    }
}
