using Content.Client.Message;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private IClientConsoleHost _consoleHost = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            // Configure RU Chat Box - only RU OOC
            ChatRu.ChatInput.ChannelSelector.Popup.AllowedChannels = ChatSelectChannel.OOC_Ru | ChatSelectChannel.OOC | ChatSelectChannel.Admin;
            ChatRu.ChatInput.ChannelSelector.Popup.SetChannels(ChatSelectChannel.OOC_Ru);
            ChatRu.ChatInput.ChannelSelector.Select(ChatSelectChannel.OOC_Ru);
            foreach (ChatChannel channel in Enum.GetValues(typeof(ChatChannel)))
            {
                if (channel != ChatChannel.None && channel != ChatChannel.IC && channel != ChatChannel.AdminRelated && channel != ChatChannel.Unspecified)
                    ChatRu.ChatInput.FilterButton.Popup.SetActive(channel, channel == ChatChannel.OOC_Ru || channel == ChatChannel.OOC || channel == ChatChannel.Server || channel == ChatChannel.Notifications || channel == ChatChannel.AdminChat || channel == ChatChannel.Admin || channel == ChatChannel.AdminAlert);
            }

            // Configure EN Chat Box - only EN OOC
            ChatEn.ChatInput.ChannelSelector.Popup.AllowedChannels = ChatSelectChannel.OOC_En | ChatSelectChannel.OOC | ChatSelectChannel.Admin;
            ChatEn.ChatInput.ChannelSelector.Popup.SetChannels(ChatSelectChannel.OOC_En);
            ChatEn.ChatInput.ChannelSelector.Select(ChatSelectChannel.OOC_En);
            foreach (ChatChannel channel in Enum.GetValues(typeof(ChatChannel)))
            {
                if (channel != ChatChannel.None && channel != ChatChannel.IC && channel != ChatChannel.AdminRelated && channel != ChatChannel.Unspecified)
                    ChatEn.ChatInput.FilterButton.Popup.SetActive(channel, channel == ChatChannel.OOC_En || channel == ChatChannel.OOC || channel == ChatChannel.Server || channel == ChatChannel.Notifications || channel == ChatChannel.AdminChat || channel == ChatChannel.Admin || channel == ChatChannel.AdminAlert);
            }

            ChatTabs.SetTabTitle(0, "RU");
            ChatTabs.SetTabTitle(1, "ENG");

            // Auto-switch channel on tab change
            ChatTabs.OnTabChanged += _ =>
            {
                ChatBox chatBox = ChatTabs.CurrentTab == 0 ? ChatRu : ChatEn;
                chatBox.ChatInput.ChannelSelector.Select(
                    ChatTabs.CurrentTab == 0 ? ChatSelectChannel.OOC_Ru : ChatSelectChannel.OOC_En);
            };

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
