using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using System.Numerics;

namespace Content.Client.Nibiru.Key.UI;

[GenerateTypedNameReferences]
public sealed partial class KeyCodeSet : FancyWindow
{
    public event Action<int>? OnCodeSubmitted;
    public event Action? OnCancelled;

    private readonly LineEdit _codeInput;

    public KeyCodeSet()
    {
        Title = Loc.GetString("lock-code-window-title");
        MinSize = new Vector2(300, 150);
        Margin = new Thickness(5);

        var vBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(10),
            HorizontalExpand = false,
            VerticalExpand = false
        };

        var label = new Label
        {
            MinWidth = 5,
            VerticalAlignment = Control.VAlignment.Top,
            HorizontalAlignment = Control.HAlignment.Left,
            Text = Loc.GetString("lock-code-window-prompt"),
            Margin = new Thickness(0, 10, 0, 10)
        };

        _codeInput = new LineEdit
        {
            PlaceHolder = Loc.GetString("lock-code-window-placeholder"),
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 10)
        };

        _codeInput.OnTextEntered += _ => SubmitCode();

        var buttonBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalAlignment = Control.HAlignment.Right
        };

        var confirmButton = new Button
        {
            Text = Loc.GetString("lock-code-window-confirm"),
            Margin = new Thickness(0, 0, 5, 0)
        };
        confirmButton.OnPressed += _ => SubmitCode();

        var cancelButton = new Button
        {
            Text = Loc.GetString("lock-code-window-cancel")
        };
        cancelButton.OnPressed += _ => Cancel();

        vBox.AddChild(label);
        vBox.AddChild(_codeInput);
        buttonBox.AddChild(confirmButton);
        buttonBox.AddChild(cancelButton);
        vBox.AddChild(buttonBox);
        AddChild(vBox);

        _codeInput.OnTextChanged += _ =>
        {
            if (_codeInput.Text.Length > 5)
            {
                _codeInput.Text = _codeInput.Text.Substring(0, 5);
            }
        };
    }

    private void SubmitCode()
    {
        if (int.TryParse(_codeInput.Text, out var code))
        {
            OnCodeSubmitted?.Invoke(code);
        }
        else if (string.IsNullOrWhiteSpace(_codeInput.Text))
        {
            // Empty input = 00000
            OnCodeSubmitted?.Invoke(0);
        }
        else
        {
            // Invalid input, show error
            _codeInput.Text = "";
            _codeInput.PlaceHolder = Loc.GetString("lock-code-window-invalid");
        }
    }

    private void Cancel()
    {
        OnCancelled?.Invoke();
    }

    protected override void Opened()
    {
        base.Opened();
        _codeInput.GrabKeyboardFocus();
    }
}
