using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Nibiru.Key.UI;

[GenerateTypedNameReferences]
public sealed partial class KeyCodeSet : DefaultWindow
{
    public event Action<string>? OnSetCode;
    public KeyCodeSet()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AcceptButton.OnPressed += _ => OnSetCode?.Invoke(CodeLabel.Text);
    }
}
