using System.Linq;
using Content.Shared._Nibiru.Factions;
using Content.Shared._Nibiru.Factions.Messeges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Maths;
using System.Numerics;
using Robust.Client.Graphics;
using Robust.Shared.Input;

namespace Content.Client.UserInterface.Systems.Faction.UI;

[GenerateTypedNameReferences]
public sealed partial class FactionLogoEditorWindow : DefaultWindow
{
    private Color _brushColor = Color.White;
    private Color _bgColor = Color.Transparent;
    private Color[] _pixels = new Color[32 * 32];
    private PanelContainer[] _pixelPanels = new PanelContainer[32 * 32];
    private bool _isDrawing = false;
    private bool _isRightDrawing = false;
    private bool _showGrid = false;
    private bool _invertGrid = false;

    public event Action<Color, List<Color>>? OnSaveLogo;

    public FactionLogoEditorWindow()
    {
        RobustXamlLoader.Load(this);

        for (int i = 0; i < 32 * 32; i++)
        {
            _pixels[i] = Color.Transparent;
            var panel = new PanelContainer
            {
                MinSize = new Vector2(10, 10),
                MaxSize = new Vector2(10, 10),
                MouseFilter = MouseFilterMode.Pass // We handle input in a background panel, or handle it per panel. Let's use Stop.
            };
            panel.MouseFilter = MouseFilterMode.Stop;

            var idx = i;
            panel.OnKeyBindDown += args =>
            {
                if (args.Function == EngineKeyFunctions.UIClick)
                {
                    _isDrawing = true;
                    SetPixel(idx, EraserButton.Pressed ? Color.Transparent : _brushColor);
                }
                else if (args.Function == EngineKeyFunctions.UIRightClick)
                {
                    _isRightDrawing = true;
                    SetPixel(idx, Color.Transparent);
                }
            };
            
            panel.OnKeyBindUp += args =>
            {
                if (args.Function == EngineKeyFunctions.UIClick)
                    _isDrawing = false;
                else if (args.Function == EngineKeyFunctions.UIRightClick)
                    _isRightDrawing = false;
            };

            panel.OnMouseEntered += args =>
            {
                if (_isDrawing)
                {
                    SetPixel(idx, EraserButton.Pressed ? Color.Transparent : _brushColor);
                }
                else if (_isRightDrawing)
                {
                    SetPixel(idx, Color.Transparent);
                }
            };

            // Добавляем границы для визуальной сетки
            panel.PanelOverride = new StyleBoxFlat 
            { 
                BackgroundColor = Color.Transparent, 
                BorderColor = new Color(50, 50, 50, 100), 
                BorderThickness = new Thickness(1) 
            };

            _pixelPanels[i] = panel;
            PixelGrid.AddChild(panel);
            UpdatePixelVisual(idx);
        }

        // Выход мыши за пределы всей сетки должен сбрасывать рисование, чтобы не залипало
        PixelGrid.OnMouseExited += args =>
        {
            // Не сбрасываем, если мышь просто перешла на другой пиксель, 
            // но в SS14 OnMouseExited срабатывает когда покидает GridContainer
        };
        
        // Но надежнее сбрасывать при отпускании мыши глобально, если получится. 
        // Если кнопка отпущена за пределами контрола, OnKeyBindUp вызывается на том контроле, где был Down.

        /*
        ToggleGridButton.OnPressed += _ =>
        {
            _showGrid = !_showGrid;
            ToggleGridButton.Text = _showGrid ? "Сетка: Вкл" : "Сетка: Выкл";
            for (int i = 0; i < 32 * 32; i++)
                UpdatePixelVisual(i);
        };

        InvertGridButton.OnPressed += _ =>
        {
            _invertGrid = !_invertGrid;
            for (int i = 0; i < 32 * 32; i++)
                UpdatePixelVisual(i);
        };
        */

        BgColorButton.OnPressed += _ =>
        {
            _bgColor = ColorSelector.Color;
            for (int i = 0; i < 32 * 32; i++)
                UpdatePixelVisual(i);
        };

        BrushColorButton.OnPressed += _ =>
        {
            _brushColor = ColorSelector.Color;
            EraserButton.Pressed = false;
        };

        ClearButton.OnPressed += _ =>
        {
            for (int i = 0; i < 32 * 32; i++)
            {
                SetPixel(i, Color.Transparent);
            }
        };

        SaveButton.OnPressed += _ =>
        {
            OnSaveLogo?.Invoke(_bgColor, _pixels.ToList());
            Close();
        };
    }

    public void LoadLogo(Color bg, List<Color> pixels)
    {
        _bgColor = bg;
        if (pixels != null && pixels.Count == 32 * 32)
        {
            for (int i = 0; i < 32 * 32; i++)
            {
                _pixels[i] = pixels[i];
                UpdatePixelVisual(i);
            }
        }
        else
        {
            for (int i = 0; i < 32 * 32; i++)
            {
                _pixels[i] = Color.Transparent;
                UpdatePixelVisual(i);
            }
        }
    }

    private void SetPixel(int index, Color color)
    {
        _pixels[index] = color;
        UpdatePixelVisual(index);
    }

    private void UpdatePixelVisual(int index)
    {
        var color = _pixels[index] == Color.Transparent ? _bgColor : _pixels[index];
        // Если фон и пиксель прозрачные, показываем сетку шахматную или темно-серый
        if (color == Color.Transparent)
        {
            // Шахматный узор для прозрачности
            bool isDark = ((index % 32) + (index / 32)) % 2 == 0;
            color = isDark ? new Color(40, 40, 40) : new Color(30, 30, 30);
        }

        Color borderColor = Color.Transparent;
        if (_showGrid)
        {
            borderColor = _invertGrid ? new Color(255, 255, 255, 100) : new Color(0, 0, 0, 100);
        }

        _pixelPanels[index].PanelOverride = new StyleBoxFlat 
        { 
            BackgroundColor = color,
            BorderColor = borderColor, 
            BorderThickness = new Thickness(1) 
        };
    }
}
