using Content.Shared._Nibiru.Factions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Faction.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class FactionMenu : DefaultWindow
    {
        //public event Action<string>? OnLabelChanged;

        /// <summary>
        /// Is the user currently entering text into the control?
        /// </summary>
        private bool _focused;
        // TODO LineEdit Make this a bool on the LineEdit control

        public string _label = string.Empty;

        public FactionMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            LabelLineEdit.OnTextChanged += e =>
            {
                _label = e.Text;
            };

            LabelLineEdit.OnFocusEnter += _ => _focused = true;
            LabelLineEdit.OnFocusExit += _ =>
            {
                _focused = false;
                LabelLineEdit.Text = _label;
            };

            var statuses = Enum.GetValues<FactionStatus>();
            FactionStatusDropdown.Clear();

            foreach (var status in statuses)
            {
                var localizedName = status switch
                {
                    FactionStatus.Active => Loc.GetString("faction-status-active"),
                    FactionStatus.Recruiting => Loc.GetString("faction-status-recruiting"),
                    FactionStatus.AtWar => Loc.GetString("faction-status-at-war"),
                    _ => status.ToString()
                };

                FactionStatusDropdown.AddItem(localizedName, (int)status);
            }
        }

        protected override void Opened()
        {
            base.Opened();

            //LabelLineEdit.GrabKeyboardFocus();
        }

        public void SetCurrentLabel(string label)
        {
            if (label == _label)
                return;

            _label = label;
            if (!_focused)
                LabelLineEdit.Text = label;
        }

        public void SetMaxLabelLength(int maxLength)
        {
            LabelLineEdit.IsValid = s => s.Length <= maxLength;
        }
    }
}
