using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared._Nibiru.Factions;
using Content.Shared._Nibiru.Factions.Messeges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Maths;
using System.Numerics;
using Robust.Client.Graphics;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.ContentPack;
using Robust.Shared.Utility;
using Robust.Shared.Log;
using Color = Robust.Shared.Maths.Color;
using Robust.Client.ResourceManagement;

namespace Content.Client.UserInterface.Systems.Faction.UI;

[GenerateTypedNameReferences]
public sealed partial class FactionLogoEditorWindow : DefaultWindow
{
    private Color _brushColor = Color.White;
    private Color _bgColor = Color.Transparent;

    private Color[] _pixels = new Color[16 * 16];
    private PanelContainer[] _pixelPanels = new PanelContainer[16 * 16];

    private Color[] _pixels8x8 = new Color[8 * 8];
    private PanelContainer[] _pixelPanels8x8 = new PanelContainer[8 * 8];

    private bool _isDrawing = false;
    private bool _isRightDrawing = false;

    public event Action<Color, List<Color>, List<Color>>? OnSaveLogo;

    public FactionLogoEditorWindow()
    {
        RobustXamlLoader.Load(this);

        for (int i = 0; i < 16 * 16; i++)
        {
            _pixels[i] = Color.Transparent;
            var panel = CreatePixelPanel(i, 16);
            _pixelPanels[i] = panel;
            PixelGrid.AddChild(panel);
            UpdatePixelVisual(i, 16);
        }

        for (int i = 0; i < 8 * 8; i++)
        {
            _pixels8x8[i] = Color.Transparent;
            var panel = CreatePixelPanel(i, 8);
            _pixelPanels8x8[i] = panel;
            PixelGrid8x8.AddChild(panel);
            UpdatePixelVisual(i, 8);
        }

        BgColorButton.OnPressed += _ =>
        {
            _bgColor = ColorSelector.Color;
            UpdatePreviews();
            RefreshAllVisuals();
        };

        BrushColorButton.OnPressed += _ =>
        {
            _brushColor = ColorSelector.Color;
            EraserButton.Pressed = false;
            UpdatePreviews();
        };

        ClearButton.OnPressed += _ =>
        {
            for (int i = 0; i < 16 * 16; i++) SetPixel(i, Color.Transparent, 16);
        };

        Clear8x8Button.OnPressed += _ =>
        {
            for (int i = 0; i < 8 * 8; i++) SetPixel(i, Color.Transparent, 8);
        };

        SaveButton.OnPressed += _ =>
        {
            OnSaveLogo?.Invoke(_bgColor, _pixels.ToList(), _pixels8x8.ToList());
            Close();
        };

        UpdatePreviews();
        PopulatePresets();
    }

    private PanelContainer CreatePixelPanel(int index, int size)
    {
        float pSize = size == 16 ? 20f : 15f;
        var panel = new PanelContainer
        {
            MinSize = new Vector2(pSize, pSize),
            MaxSize = new Vector2(pSize, pSize),
            MouseFilter = MouseFilterMode.Stop
        };

        panel.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick)
            {
                _isDrawing = true;
                SetPixel(index, EraserButton.Pressed ? Color.Transparent : _brushColor, size);
            }
            else if (args.Function == EngineKeyFunctions.UIRightClick)
            {
                _isRightDrawing = true;
                SetPixel(index, Color.Transparent, size);
            }
        };

        panel.OnKeyBindUp += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick) _isDrawing = false;
            else if (args.Function == EngineKeyFunctions.UIRightClick) _isRightDrawing = false;
        };

        panel.OnMouseEntered += _ =>
        {
            if (_isDrawing) SetPixel(index, EraserButton.Pressed ? Color.Transparent : _brushColor, size);
            else if (_isRightDrawing) SetPixel(index, Color.Transparent, size);
        };

        return panel;
    }

    private void UpdatePreviews()
    {
        if (BrushPreview.PanelOverride is StyleBoxFlat brushStyle) brushStyle.BackgroundColor = _brushColor;
        if (BgPreview.PanelOverride is StyleBoxFlat bgStyle) bgStyle.BackgroundColor = _bgColor;
    }

    private void RefreshAllVisuals()
    {
        for (int i = 0; i < 16 * 16; i++) UpdatePixelVisual(i, 16);
        for (int i = 0; i < 8 * 8; i++) UpdatePixelVisual(i, 8);
    }

    public void LoadLogo(Color bg, List<Color> pixels16, List<Color> pixels8)
    {
        _bgColor = bg;
        LoadPixels(pixels16, _pixels, 16);
        LoadPixels(pixels8, _pixels8x8, 8);
        UpdatePreviews();
        RefreshAllVisuals();
    }

    private void LoadPixels(List<Color> source, Color[] target, int size)
    {
        int count = size * size;
        if (source != null && source.Count == count)
        {
            for (int i = 0; i < count; i++) target[i] = source[i];
        }
        else
        {
            for (int i = 0; i < count; i++) target[i] = Color.Transparent;
        }
    }

    private void SetPixel(int index, Color color, int size)
    {
        if (size == 16) _pixels[index] = color;
        else _pixels8x8[index] = color;
        UpdatePixelVisual(index, size);
    }

    private void UpdatePixelVisual(int index, int size)
    {
        var pixels = size == 16 ? _pixels : _pixels8x8;
        var panels = size == 16 ? _pixelPanels : _pixelPanels8x8;

        var color = pixels[index] == Color.Transparent ? _bgColor : pixels[index];
        if (color == Color.Transparent)
        {
            bool isDark = ((index % size) + (index / size)) % 2 == 0;
            color = isDark ? new Color(35, 35, 35) : new Color(25, 25, 25);
        }

        panels[index].PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = color,
            BorderColor = new Color(50, 50, 50, 40),
            BorderThickness = new Thickness(1)
        };
    }

    private void PopulatePresets()
    {
        var prototypeManager = IoCManager.Resolve<IPrototypeManager>();
        var resourceManager = IoCManager.Resolve<IResourceManager>();
        var resourceCache = IoCManager.Resolve<IResourceCache>();

        foreach (var preset in prototypeManager.EnumeratePrototypes<FactionLogoPresetPrototype>())
        {
            ResPath? file16 = preset.Sprite16;
            ResPath? file8 = preset.Sprite8;

            if (preset.SpriteFolder != null)
            {
                var folder = preset.SpriteFolder.Value;
                var folderName = folder.Filename;

                file16 ??= TryResolvePresetFile(resourceManager, folder / $"{folderName}.png");
                file16 ??= TryResolvePresetFile(resourceManager, folder / $"{folderName}_16.png");

                file8 ??= TryResolvePresetFile(resourceManager, folder / $"{folderName}_8x8.png");
                file8 ??= TryResolvePresetFile(resourceManager, folder / $"{folderName}_8.png");
            }

            if (file16 == null || file8 == null)
                continue;

            var pixels16 = LoadPixelsFromTexture(resourceCache, file16.Value, 16);
            var pixels8 = LoadPixelsFromTexture(resourceCache, file8.Value, 8);

            AddPresetButton(Loc.GetString(preset.Name), pixels16, pixels8);
        }
    }

    private static ResPath? TryResolvePresetFile(IResourceManager resourceManager, ResPath path)
    {
        return resourceManager.ContentFileExists(path) ? path : null;
    }

    private List<Color> LoadPixelsFromTexture(IResourceCache cache, ResPath path, int expectedSize)
    {
        var result = new List<Color>(expectedSize * expectedSize);
        var texture = cache.GetResource<TextureResource>(path).Texture;

        int width = Math.Min(texture.Width, expectedSize);
        int height = Math.Min(texture.Height, expectedSize);

        for (int y = 0; y < expectedSize; y++)
        {
            for (int x = 0; x < expectedSize; x++)
            {
                if (x < width && y < height)
                {
                    var p = texture.GetPixel(x, y);
                    if (p.A == 0)
                    {
                        result.Add(Color.Transparent);
                    }
                    else
                    {
                        result.Add(Color.White);
                    }
                }
                else
                {
                    result.Add(Color.Transparent);
                }
            }
        }

        return result;
    }

    private void AddPresetButton(string name, List<Color> pixels16, List<Color> pixels8)
    {
        var button = new Button
        {
            MinSize = new Vector2(54, 54),
            ToolTip = name,
        };

        var logoControl = new FactionLogoControl
        {
            MinSize = new Vector2(40, 40),
            MaxSize = new Vector2(40, 40),
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            MouseFilter = MouseFilterMode.Ignore
        };
        logoControl.UpdateLogo(Color.Transparent, pixels16);

        button.AddChild(logoControl);
        button.OnPressed += _ => ApplyPreset(pixels16, pixels8);

        PresetGrid.AddChild(button);
    }

    private void ApplyPreset(List<Color> pixels16, List<Color> pixels8)
    {
        for (int i = 0; i < 16 * 16; i++)
        {
            _pixels[i] = pixels16[i] != Color.Transparent ? _brushColor : Color.Transparent;
        }

        for (int i = 0; i < 8 * 8; i++)
        {
            _pixels8x8[i] = pixels8[i] != Color.Transparent ? _brushColor : Color.Transparent;
        }

        RefreshAllVisuals();
    }
}

