using Content.Client.Administration.UI.CustomControls;
using Content.Shared._Nibiru.EntityInspector;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Nibiru.EntityInspector;

[GenerateTypedNameReferences]
public sealed partial class EntityInspectorWindow : Content.Client.UserInterface.Controls.FancyWindow
{
    // ──────────────────────────────────────────────────────────
    //  Внутренний контейнер поля (уже разрешённое имя + данные)
    // ──────────────────────────────────────────────────────────

    private sealed class ResolvedField
    {
        public string  DisplayName { get; init; } = string.Empty;
        public string? Detail      { get; init; }
        public object? Value       { get; init; }
    }

    // ──────────────────────────────────────────────────────────
    //  Конструктор
    // ──────────────────────────────────────────────────────────

    public EntityInspectorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    // ──────────────────────────────────────────────────────────
    //  Публичный API
    // ──────────────────────────────────────────────────────────

    /// <summary>
    /// Заполняет окно данными сущности. Вызывается из EntityInspectorSystem.
    /// </summary>
    public void Populate(string entityName, IEnumerable<IComponent> components, bool isOwner)
    {
        EntityNameLabel.Text = entityName;
        Title = Loc.GetString("entity-inspector-window-title", ("name", entityName));

        ComponentList.RemoveAllChildren();
        ClearDetail();

        foreach (var component in components)
        {
            if (component is not IInspectableComponent inspectable)
                continue;

            // Имя компонента: пробуем как ключ локализации, затем сырое значение
            var rawName  = inspectable.InspectorDisplayName;
            var compName = string.IsNullOrEmpty(rawName)
                ? FormatTypeName(component.GetType().Name)
                : TryLoc(rawName) ?? rawName;

            // Собираем поля
            var fields = new List<ResolvedField>();
            foreach (var fd in inspectable.GetInspectableFields())
            {
                if (fd.RequireOwnership && !isOwner)
                    continue;

                fields.Add(new ResolvedField
                {
                    DisplayName = TryLoc(fd.DisplayName) ?? fd.DisplayName,
                    Detail      = fd.Detail,
                    Value       = fd.Value,
                });
            }

            if (fields.Count == 0)
                continue;

            // Сортируем по Order (поля уже в порядке yield, но пересортируем если нужно)
            // fields уже упорядочены по Order через yield-порядок

            ComponentList.AddChild(BuildComponentSection(compName, fields));
        }

        if (ComponentList.ChildCount == 0)
        {
            ComponentList.AddChild(new Label
            {
                Text = Loc.GetString("entity-inspector-no-components"),
                FontColorOverride = Color.FromHex("#888888"),
                Margin = new Thickness(8, 12),
                HorizontalAlignment = HAlignment.Center,
            });
        }
    }

    // ──────────────────────────────────────────────────────────
    //  Построение секции компонента
    // ──────────────────────────────────────────────────────────

    private Control BuildComponentSection(string compName, List<ResolvedField> fields)
    {
        var section = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            SeparationOverride = 0,
        };

        // ── Заголовок-кнопка (сворачивает / разворачивает) ────
        var header = new Button
        {
            HorizontalExpand = true,
            ToggleMode       = true,
            Pressed          = true,
        };
        header.AddStyleClass("OpenRight");

        var headerLabel = new Label
        {
            Text = $"▾  {compName}",
            StyleClasses = { "LabelHeading" },
            HorizontalExpand = true,
            Margin = new Thickness(4, 2),
        };
        header.AddChild(headerLabel);
        section.AddChild(header);

        // ── Контейнер строк полей ──────────────────────────────
        var fieldsBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 4),
            SeparationOverride = 0,
            Visible = true,
        };
        section.AddChild(fieldsBox);

        header.OnToggled += args =>
        {
            fieldsBox.Visible   = args.Pressed;
            headerLabel.Text    = args.Pressed ? $"▾  {compName}" : $"▶  {compName}";
        };

        foreach (var field in fields)
            fieldsBox.AddChild(BuildFieldRow(field));

        return section;
    }

    private Control BuildFieldRow(ResolvedField field)
    {
        var valueStr = FormatValue(field.Value);

        var row = new ContainerButton
        {
            HorizontalExpand = true,
        };
        row.AddStyleClass("ExamineButton");

        var rowBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(14, 3, 6, 3),
        };

        rowBox.AddChild(new Label
        {
            Text = field.DisplayName,
            MinWidth = 120,
            ClipText = true,
            FontColorOverride = Color.FromHex("#C8C8FF"),
        });

        rowBox.AddChild(new Label
        {
            Text = valueStr,
            HorizontalExpand = true,
            ClipText = true,
            HorizontalAlignment = HAlignment.Right,
            FontColorOverride = Color.FromHex("#FFFFFF"),
        });

        row.AddChild(rowBox);
        row.OnPressed += _ => SelectField(field);

        return row;
    }

    // ──────────────────────────────────────────────────────────
    //  Правая панель деталей
    // ──────────────────────────────────────────────────────────

    private void SelectField(ResolvedField field)
    {
        DetailPlaceholder.Visible = false;
        DetailTitleLabel.Text     = field.DisplayName;

        // Очищаем предыдущий контент (кроме Placeholder)
        for (var i = DetailContainer.ChildCount - 1; i >= 0; i--)
        {
            var child = DetailContainer.GetChild(i);
            if (child == DetailPlaceholder)
                continue;
            DetailContainer.RemoveChild(child);
        }

        // ── Значение ──────────────────────────────────────────
        AddDetailRow(Loc.GetString("entity-inspector-detail-value"), FormatValue(field.Value));

        // ── Описание из атрибута ──────────────────────────────
        if (field.Detail is { Length: > 0 } rawDetail)
        {
            DetailContainer.AddChild(new HSeparator { Margin = new Thickness(0, 6) });

            var resolved   = TryLoc(rawDetail) ?? rawDetail;
            var detailLabel = new RichTextLabel { HorizontalExpand = true };
            detailLabel.SetMessage(FormattedMessage.FromMarkupPermissive(resolved));
            DetailContainer.AddChild(detailLabel);
        }

        // ── Если значение — коллекция, перечисляем элементы ──
        if (field.Value is System.Collections.IEnumerable enumerable and not string)
        {
            DetailContainer.AddChild(new HSeparator { Margin = new Thickness(0, 6) });

            DetailContainer.AddChild(new Label
            {
                Text = Loc.GetString("entity-inspector-detail-contents"),
                FontColorOverride = Color.FromHex("#AAAAAA"),
                Margin = new Thickness(0, 2),
            });

            var count = 0;
            foreach (var item in enumerable)
            {
                AddDetailRow($"[{count}]", item?.ToString() ?? "<null>");
                count++;
                if (count >= 50)
                {
                    AddDetailRow("...", Loc.GetString("entity-inspector-detail-more", ("count", count)));
                    break;
                }
            }

            if (count == 0)
                AddDetailRow(Loc.GetString("entity-inspector-detail-empty"), string.Empty);
        }
    }

    private void AddDetailRow(string label, string? value)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8,
        };

        row.AddChild(new Label
        {
            Text = label,
            FontColorOverride = Color.FromHex("#888888"),
            MinWidth = 90,
            ClipText = true,
        });

        row.AddChild(new Label
        {
            Text = value ?? "<null>",
            HorizontalExpand = true,
            ClipText = true,
            FontColorOverride = Color.FromHex("#FFFFFF"),
        });

        DetailContainer.AddChild(row);
    }

    private void ClearDetail()
    {
        DetailTitleLabel.Text     = Loc.GetString("entity-inspector-select-field");
        DetailPlaceholder.Visible = true;

        for (var i = DetailContainer.ChildCount - 1; i >= 0; i--)
        {
            var child = DetailContainer.GetChild(i);
            if (child == DetailPlaceholder)
                continue;
            DetailContainer.RemoveChild(child);
        }
    }

    // ──────────────────────────────────────────────────────────
    //  Вспомогательные методы (нет рефлексии)
    // ──────────────────────────────────────────────────────────

    private static string FormatValue(object? value)
    {
        if (value is null)   return Loc.GetString("entity-inspector-value-null");
        if (value is bool b) return b ? Loc.GetString("entity-inspector-value-yes")
                                      : Loc.GetString("entity-inspector-value-no");
        if (value is string s) return s.Length == 0
            ? Loc.GetString("entity-inspector-value-empty")
            : s;

        if (value is System.Collections.ICollection col)
            return Loc.GetString("entity-inspector-value-collection", ("count", col.Count));

        if (value is System.Collections.IEnumerable and not string)
            return Loc.GetString("entity-inspector-value-list");

        var str = value.ToString() ?? string.Empty;
        return str.Length > 40 ? str[..37] + "…" : str;
    }

    /// <summary>
    /// Пробует перевести строку через Loc.
    /// Если ключ не найден в Fluent — возвращает null (используй исходную строку как fallback).
    /// </summary>
    private static string? TryLoc(string key)
    {
        if (string.IsNullOrEmpty(key))
            return null;
        var result = Loc.GetString(key);
        // Fluent возвращает ключ обёрнутым если не найден
        return (result == key || result.StartsWith('{')) ? null : result;
    }

    /// <summary>Убирает суффикс «Component» из имени класса.</summary>
    private static string FormatTypeName(string typeName)
    {
        const string suffix = "Component";
        return typeName.EndsWith(suffix, StringComparison.Ordinal)
            ? typeName[..^suffix.Length]
            : typeName;
    }
}
