name: "Labels: Changes"

on:
  pull_request_review:
    types: [submitted]

jobs:
  update_label:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        sparse-checkout: .github/actions/pr-labels
    - uses: ./.github/actions/pr-labels
      with:
        add: |
          Статус: Ожидает правок
        remove: |
          Статус: Нужно ревью
          Status: Needs Review
          S: Needs Review
