name: "Лейблы: Правки"

on:
  pull_request_review:
    types: [submitted]

jobs:
  update_label:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Статус: Ожидает правок"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: |
          Статус: Нужно ревью
          Status: Needs Review
          S: Needs Review
