name: "Лейблы: Одобрение"

on:
  pull_request_review:
    types: [submitted]

jobs:
  remove_label:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        sparse-checkout: .github/actions/pr-labels
    - uses: ./.github/actions/pr-labels
      with:
        remove: |
          Статус: Нужно ревью
          Статус: Ожидает правок
          Status: Needs Review
          Status: Awaiting Changes
          S: Needs Review
          S: Awaiting Changes
