name: "Labels: Branch staging"

on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'staging'

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        sparse-checkout: .github/actions/pr-labels
    - uses: ./.github/actions/pr-labels
      with:
        add: |
          Ветка: Staging
