name: "Лейблы: Одобрение"

on:
  pull_request_review:
    types: [submitted]

jobs:
  remove_label:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: |
          Статус: Нужно ревью
          Статус: Ожидает правок
          Status: Needs Review
          Status: Awaiting Changes
          S: Needs Review
          S: Awaiting Changes
