name: "Labels: Review"

on:
  pull_request_target:
    types: [review_requested, opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
        sparse-checkout: .github/actions/pr-labels
    - uses: ./.github/actions/pr-labels
      with:
        add: |
          Статус: Нужно ревью
        remove: |
          Статус: Ожидает правок
          Status: Awaiting Changes
          S: Awaiting Changes
          S: Needs Review
          Status: Needs Review
